/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.game.core.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.trantorinc.synergy.game.core.model.GameTimeline;
import com.trantorinc.synergy.game.core.service.GameTimelineLocalService;
import com.trantorinc.synergy.game.core.service.GameTimelineLocalServiceUtil;
import com.trantorinc.synergy.game.core.service.persistence.GameTimelinePersistence;
import com.trantorinc.synergy.game.core.service.persistence.PrizeFinder;
import com.trantorinc.synergy.game.core.service.persistence.PrizePersistence;
import com.trantorinc.synergy.game.core.service.persistence.SantaFinder;
import com.trantorinc.synergy.game.core.service.persistence.SantaPersistence;
import com.trantorinc.synergy.game.core.service.persistence.TicketFinder;
import com.trantorinc.synergy.game.core.service.persistence.TicketPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the game timeline local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.trantorinc.synergy.game.core.service.impl.GameTimelineLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.trantorinc.synergy.game.core.service.impl.GameTimelineLocalServiceImpl
 * @generated
 */
public abstract class GameTimelineLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GameTimelineLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GameTimelineLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GameTimelineLocalServiceUtil</code>.
	 */

	/**
	 * Adds the game timeline to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GameTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gameTimeline the game timeline
	 * @return the game timeline that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GameTimeline addGameTimeline(GameTimeline gameTimeline) {
		gameTimeline.setNew(true);

		return gameTimelinePersistence.update(gameTimeline);
	}

	/**
	 * Creates a new game timeline with the primary key. Does not add the game timeline to the database.
	 *
	 * @param name the primary key for the new game timeline
	 * @return the new game timeline
	 */
	@Override
	@Transactional(enabled = false)
	public GameTimeline createGameTimeline(String name) {
		return gameTimelinePersistence.create(name);
	}

	/**
	 * Deletes the game timeline with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GameTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param name the primary key of the game timeline
	 * @return the game timeline that was removed
	 * @throws PortalException if a game timeline with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GameTimeline deleteGameTimeline(String name) throws PortalException {
		return gameTimelinePersistence.remove(name);
	}

	/**
	 * Deletes the game timeline from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GameTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gameTimeline the game timeline
	 * @return the game timeline that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GameTimeline deleteGameTimeline(GameTimeline gameTimeline) {
		return gameTimelinePersistence.remove(gameTimeline);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return gameTimelinePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			GameTimeline.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return gameTimelinePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.game.core.model.impl.GameTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return gameTimelinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.game.core.model.impl.GameTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return gameTimelinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return gameTimelinePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return gameTimelinePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public GameTimeline fetchGameTimeline(String name) {
		return gameTimelinePersistence.fetchByPrimaryKey(name);
	}

	/**
	 * Returns the game timeline with the primary key.
	 *
	 * @param name the primary key of the game timeline
	 * @return the game timeline
	 * @throws PortalException if a game timeline with the primary key could not be found
	 */
	@Override
	public GameTimeline getGameTimeline(String name) throws PortalException {
		return gameTimelinePersistence.findByPrimaryKey(name);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gameTimelinePersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement GameTimelineLocalServiceImpl#deleteGameTimeline(GameTimeline) to avoid orphaned data");
		}

		return gameTimelineLocalService.deleteGameTimeline(
			(GameTimeline)persistedModel);
	}

	@Override
	public BasePersistence<GameTimeline> getBasePersistence() {
		return gameTimelinePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gameTimelinePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the game timelines.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.game.core.model.impl.GameTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of game timelines
	 * @param end the upper bound of the range of game timelines (not inclusive)
	 * @return the range of game timelines
	 */
	@Override
	public List<GameTimeline> getGameTimelines(int start, int end) {
		return gameTimelinePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of game timelines.
	 *
	 * @return the number of game timelines
	 */
	@Override
	public int getGameTimelinesCount() {
		return gameTimelinePersistence.countAll();
	}

	/**
	 * Updates the game timeline in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GameTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param gameTimeline the game timeline
	 * @return the game timeline that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GameTimeline updateGameTimeline(GameTimeline gameTimeline) {
		return gameTimelinePersistence.update(gameTimeline);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GameTimelineLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		gameTimelineLocalService = (GameTimelineLocalService)aopProxy;

		_setLocalServiceUtilService(gameTimelineLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GameTimelineLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return GameTimeline.class;
	}

	protected String getModelClassName() {
		return GameTimeline.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = gameTimelinePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		GameTimelineLocalService gameTimelineLocalService) {

		try {
			Field field = GameTimelineLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, gameTimelineLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected GameTimelineLocalService gameTimelineLocalService;

	@Reference
	protected GameTimelinePersistence gameTimelinePersistence;

	@Reference
	protected PrizePersistence prizePersistence;

	@Reference
	protected PrizeFinder prizeFinder;

	@Reference
	protected SantaPersistence santaPersistence;

	@Reference
	protected SantaFinder santaFinder;

	@Reference
	protected TicketPersistence ticketPersistence;

	@Reference
	protected TicketFinder ticketFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		GameTimelineLocalServiceBaseImpl.class);

}