/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.KpiLine;
import com.trantorinc.synergy.performance.core.model.KpiLineModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KpiLine service. Represents a row in the &quot;PERFORMANCE_KpiLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KpiLineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KpiLineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KpiLineImpl
 * @generated
 */
public class KpiLineModelImpl
	extends BaseModelImpl<KpiLine> implements KpiLineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kpi line model instance should use the <code>KpiLine</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_KpiLine";

	public static final Object[][] TABLE_COLUMNS = {
		{"lineId", Types.BIGINT}, {"kpiId", Types.BIGINT},
		{"guideId", Types.BIGINT}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"target", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kpiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("guideId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("target", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_KpiLine (lineId LONG not null primary key,kpiId LONG,guideId LONG,title VARCHAR(75) null,description TEXT null,target TEXT null,createDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_KpiLine";

	public static final String ORDER_BY_JPQL = " ORDER BY kpiLine.lineId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_KpiLine.lineId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LINEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public KpiLineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KpiLine.class;
	}

	@Override
	public String getModelClassName() {
		return KpiLine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KpiLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KpiLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KpiLine, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((KpiLine)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KpiLine, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KpiLine, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KpiLine)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KpiLine, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KpiLine, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<KpiLine, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<KpiLine, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<KpiLine, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<KpiLine, Object>>();
		Map<String, BiConsumer<KpiLine, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<KpiLine, ?>>();

		attributeGetterFunctions.put("lineId", KpiLine::getLineId);
		attributeSetterBiConsumers.put(
			"lineId", (BiConsumer<KpiLine, Long>)KpiLine::setLineId);
		attributeGetterFunctions.put("kpiId", KpiLine::getKpiId);
		attributeSetterBiConsumers.put(
			"kpiId", (BiConsumer<KpiLine, Long>)KpiLine::setKpiId);
		attributeGetterFunctions.put("guideId", KpiLine::getGuideId);
		attributeSetterBiConsumers.put(
			"guideId", (BiConsumer<KpiLine, Long>)KpiLine::setGuideId);
		attributeGetterFunctions.put("title", KpiLine::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<KpiLine, String>)KpiLine::setTitle);
		attributeGetterFunctions.put("description", KpiLine::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<KpiLine, String>)KpiLine::setDescription);
		attributeGetterFunctions.put("target", KpiLine::getTarget);
		attributeSetterBiConsumers.put(
			"target", (BiConsumer<KpiLine, String>)KpiLine::setTarget);
		attributeGetterFunctions.put("createDate", KpiLine::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<KpiLine, Date>)KpiLine::setCreateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLineId() {
		return _lineId;
	}

	@Override
	public void setLineId(long lineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lineId = lineId;
	}

	@Override
	public long getKpiId() {
		return _kpiId;
	}

	@Override
	public void setKpiId(long kpiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kpiId = kpiId;
	}

	@Override
	public long getGuideId() {
		return _guideId;
	}

	@Override
	public void setGuideId(long guideId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_guideId = guideId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getTarget() {
		if (_target == null) {
			return "";
		}
		else {
			return _target;
		}
	}

	@Override
	public void setTarget(String target) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_target = target;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, KpiLine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KpiLine toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KpiLine>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KpiLineImpl kpiLineImpl = new KpiLineImpl();

		kpiLineImpl.setLineId(getLineId());
		kpiLineImpl.setKpiId(getKpiId());
		kpiLineImpl.setGuideId(getGuideId());
		kpiLineImpl.setTitle(getTitle());
		kpiLineImpl.setDescription(getDescription());
		kpiLineImpl.setTarget(getTarget());
		kpiLineImpl.setCreateDate(getCreateDate());

		kpiLineImpl.resetOriginalValues();

		return kpiLineImpl;
	}

	@Override
	public KpiLine cloneWithOriginalValues() {
		KpiLineImpl kpiLineImpl = new KpiLineImpl();

		kpiLineImpl.setLineId(this.<Long>getColumnOriginalValue("lineId"));
		kpiLineImpl.setKpiId(this.<Long>getColumnOriginalValue("kpiId"));
		kpiLineImpl.setGuideId(this.<Long>getColumnOriginalValue("guideId"));
		kpiLineImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		kpiLineImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		kpiLineImpl.setTarget(this.<String>getColumnOriginalValue("target"));
		kpiLineImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));

		return kpiLineImpl;
	}

	@Override
	public int compareTo(KpiLine kpiLine) {
		long primaryKey = kpiLine.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KpiLine)) {
			return false;
		}

		KpiLine kpiLine = (KpiLine)object;

		long primaryKey = kpiLine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KpiLine> toCacheModel() {
		KpiLineCacheModel kpiLineCacheModel = new KpiLineCacheModel();

		kpiLineCacheModel.lineId = getLineId();

		kpiLineCacheModel.kpiId = getKpiId();

		kpiLineCacheModel.guideId = getGuideId();

		kpiLineCacheModel.title = getTitle();

		String title = kpiLineCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			kpiLineCacheModel.title = null;
		}

		kpiLineCacheModel.description = getDescription();

		String description = kpiLineCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			kpiLineCacheModel.description = null;
		}

		kpiLineCacheModel.target = getTarget();

		String target = kpiLineCacheModel.target;

		if ((target != null) && (target.length() == 0)) {
			kpiLineCacheModel.target = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			kpiLineCacheModel.createDate = createDate.getTime();
		}
		else {
			kpiLineCacheModel.createDate = Long.MIN_VALUE;
		}

		return kpiLineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KpiLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KpiLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KpiLine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((KpiLine)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KpiLine>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					KpiLine.class, ModelWrapper.class);

	}

	private long _lineId;
	private long _kpiId;
	private long _guideId;
	private String _title;
	private String _description;
	private String _target;
	private Date _createDate;

	public <T> T getColumnValue(String columnName) {
		Function<KpiLine, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((KpiLine)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("lineId", _lineId);
		_columnOriginalValues.put("kpiId", _kpiId);
		_columnOriginalValues.put("guideId", _guideId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("target", _target);
		_columnOriginalValues.put("createDate", _createDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("lineId", 1L);

		columnBitmasks.put("kpiId", 2L);

		columnBitmasks.put("guideId", 4L);

		columnBitmasks.put("title", 8L);

		columnBitmasks.put("description", 16L);

		columnBitmasks.put("target", 32L);

		columnBitmasks.put("createDate", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private KpiLine _escapedModel;

}