/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.ReviewComment;
import com.trantorinc.synergy.performance.core.model.ReviewCommentModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReviewComment service. Represents a row in the &quot;PERFORMANCE_ReviewComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReviewCommentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewCommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewCommentImpl
 * @generated
 */
public class ReviewCommentModelImpl
	extends BaseModelImpl<ReviewComment> implements ReviewCommentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a review comment model instance should use the <code>ReviewComment</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_ReviewComment";

	public static final Object[][] TABLE_COLUMNS = {
		{"commentId", Types.BIGINT}, {"reviewId", Types.BIGINT},
		{"author", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"createdDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("author", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_ReviewComment (commentId LONG not null primary key,reviewId LONG,author VARCHAR(75) null,description TEXT null,createdDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_ReviewComment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reviewComment.commentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_ReviewComment.commentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReviewCommentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReviewComment.class;
	}

	@Override
	public String getModelClassName() {
		return ReviewComment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReviewComment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReviewComment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewComment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReviewComment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReviewComment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReviewComment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReviewComment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReviewComment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReviewComment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReviewComment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReviewComment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReviewComment, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReviewComment, Object>>();
		Map<String, BiConsumer<ReviewComment, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReviewComment, ?>>();

		attributeGetterFunctions.put("commentId", ReviewComment::getCommentId);
		attributeSetterBiConsumers.put(
			"commentId",
			(BiConsumer<ReviewComment, Long>)ReviewComment::setCommentId);
		attributeGetterFunctions.put("reviewId", ReviewComment::getReviewId);
		attributeSetterBiConsumers.put(
			"reviewId",
			(BiConsumer<ReviewComment, Long>)ReviewComment::setReviewId);
		attributeGetterFunctions.put("author", ReviewComment::getAuthor);
		attributeSetterBiConsumers.put(
			"author",
			(BiConsumer<ReviewComment, String>)ReviewComment::setAuthor);
		attributeGetterFunctions.put(
			"description", ReviewComment::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ReviewComment, String>)ReviewComment::setDescription);
		attributeGetterFunctions.put(
			"createdDate", ReviewComment::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<ReviewComment, Date>)ReviewComment::setCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCommentId() {
		return _commentId;
	}

	@Override
	public void setCommentId(long commentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commentId = commentId;
	}

	@Override
	public long getReviewId() {
		return _reviewId;
	}

	@Override
	public void setReviewId(long reviewId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewId = reviewId;
	}

	@Override
	public String getAuthor() {
		if (_author == null) {
			return "";
		}
		else {
			return _author;
		}
	}

	@Override
	public void setAuthor(String author) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_author = author;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReviewComment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReviewComment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReviewComment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReviewCommentImpl reviewCommentImpl = new ReviewCommentImpl();

		reviewCommentImpl.setCommentId(getCommentId());
		reviewCommentImpl.setReviewId(getReviewId());
		reviewCommentImpl.setAuthor(getAuthor());
		reviewCommentImpl.setDescription(getDescription());
		reviewCommentImpl.setCreatedDate(getCreatedDate());

		reviewCommentImpl.resetOriginalValues();

		return reviewCommentImpl;
	}

	@Override
	public ReviewComment cloneWithOriginalValues() {
		ReviewCommentImpl reviewCommentImpl = new ReviewCommentImpl();

		reviewCommentImpl.setCommentId(
			this.<Long>getColumnOriginalValue("commentId"));
		reviewCommentImpl.setReviewId(
			this.<Long>getColumnOriginalValue("reviewId"));
		reviewCommentImpl.setAuthor(
			this.<String>getColumnOriginalValue("author"));
		reviewCommentImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		reviewCommentImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("createdDate"));

		return reviewCommentImpl;
	}

	@Override
	public int compareTo(ReviewComment reviewComment) {
		long primaryKey = reviewComment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReviewComment)) {
			return false;
		}

		ReviewComment reviewComment = (ReviewComment)object;

		long primaryKey = reviewComment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReviewComment> toCacheModel() {
		ReviewCommentCacheModel reviewCommentCacheModel =
			new ReviewCommentCacheModel();

		reviewCommentCacheModel.commentId = getCommentId();

		reviewCommentCacheModel.reviewId = getReviewId();

		reviewCommentCacheModel.author = getAuthor();

		String author = reviewCommentCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			reviewCommentCacheModel.author = null;
		}

		reviewCommentCacheModel.description = getDescription();

		String description = reviewCommentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			reviewCommentCacheModel.description = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			reviewCommentCacheModel.createdDate = createdDate.getTime();
		}
		else {
			reviewCommentCacheModel.createdDate = Long.MIN_VALUE;
		}

		return reviewCommentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReviewComment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReviewComment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewComment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReviewComment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReviewComment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReviewComment.class, ModelWrapper.class);

	}

	private long _commentId;
	private long _reviewId;
	private String _author;
	private String _description;
	private Date _createdDate;

	public <T> T getColumnValue(String columnName) {
		Function<ReviewComment, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReviewComment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("commentId", _commentId);
		_columnOriginalValues.put("reviewId", _reviewId);
		_columnOriginalValues.put("author", _author);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("createdDate", _createdDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("commentId", 1L);

		columnBitmasks.put("reviewId", 2L);

		columnBitmasks.put("author", 4L);

		columnBitmasks.put("description", 8L);

		columnBitmasks.put("createdDate", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReviewComment _escapedModel;

}