/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.ReviewUpload;
import com.trantorinc.synergy.performance.core.model.ReviewUploadModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReviewUpload service. Represents a row in the &quot;PERFORMANCE_ReviewUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReviewUploadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewUploadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewUploadImpl
 * @generated
 */
public class ReviewUploadModelImpl
	extends BaseModelImpl<ReviewUpload> implements ReviewUploadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a review upload model instance should use the <code>ReviewUpload</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_ReviewUpload";

	public static final Object[][] TABLE_COLUMNS = {
		{"uploadId", Types.BIGINT}, {"reviewId", Types.BIGINT},
		{"attachmentName", Types.VARCHAR}, {"fileId", Types.VARCHAR},
		{"createdDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uploadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("attachmentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_ReviewUpload (uploadId LONG not null primary key,reviewId LONG,attachmentName VARCHAR(75) null,fileId VARCHAR(75) null,createdDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_ReviewUpload";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reviewUpload.uploadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_ReviewUpload.uploadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UPLOADID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReviewUploadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _uploadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUploadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _uploadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReviewUpload.class;
	}

	@Override
	public String getModelClassName() {
		return ReviewUpload.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReviewUpload, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReviewUpload, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewUpload, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReviewUpload)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReviewUpload, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReviewUpload, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReviewUpload)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReviewUpload, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReviewUpload, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReviewUpload, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReviewUpload, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReviewUpload, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReviewUpload, Object>>();
		Map<String, BiConsumer<ReviewUpload, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReviewUpload, ?>>();

		attributeGetterFunctions.put("uploadId", ReviewUpload::getUploadId);
		attributeSetterBiConsumers.put(
			"uploadId",
			(BiConsumer<ReviewUpload, Long>)ReviewUpload::setUploadId);
		attributeGetterFunctions.put("reviewId", ReviewUpload::getReviewId);
		attributeSetterBiConsumers.put(
			"reviewId",
			(BiConsumer<ReviewUpload, Long>)ReviewUpload::setReviewId);
		attributeGetterFunctions.put(
			"attachmentName", ReviewUpload::getAttachmentName);
		attributeSetterBiConsumers.put(
			"attachmentName",
			(BiConsumer<ReviewUpload, String>)ReviewUpload::setAttachmentName);
		attributeGetterFunctions.put("fileId", ReviewUpload::getFileId);
		attributeSetterBiConsumers.put(
			"fileId",
			(BiConsumer<ReviewUpload, String>)ReviewUpload::setFileId);
		attributeGetterFunctions.put(
			"createdDate", ReviewUpload::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<ReviewUpload, Date>)ReviewUpload::setCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getUploadId() {
		return _uploadId;
	}

	@Override
	public void setUploadId(long uploadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uploadId = uploadId;
	}

	@Override
	public long getReviewId() {
		return _reviewId;
	}

	@Override
	public void setReviewId(long reviewId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewId = reviewId;
	}

	@Override
	public String getAttachmentName() {
		if (_attachmentName == null) {
			return "";
		}
		else {
			return _attachmentName;
		}
	}

	@Override
	public void setAttachmentName(String attachmentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attachmentName = attachmentName;
	}

	@Override
	public String getFileId() {
		if (_fileId == null) {
			return "";
		}
		else {
			return _fileId;
		}
	}

	@Override
	public void setFileId(String fileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileId = fileId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReviewUpload.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReviewUpload toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReviewUpload>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReviewUploadImpl reviewUploadImpl = new ReviewUploadImpl();

		reviewUploadImpl.setUploadId(getUploadId());
		reviewUploadImpl.setReviewId(getReviewId());
		reviewUploadImpl.setAttachmentName(getAttachmentName());
		reviewUploadImpl.setFileId(getFileId());
		reviewUploadImpl.setCreatedDate(getCreatedDate());

		reviewUploadImpl.resetOriginalValues();

		return reviewUploadImpl;
	}

	@Override
	public ReviewUpload cloneWithOriginalValues() {
		ReviewUploadImpl reviewUploadImpl = new ReviewUploadImpl();

		reviewUploadImpl.setUploadId(
			this.<Long>getColumnOriginalValue("uploadId"));
		reviewUploadImpl.setReviewId(
			this.<Long>getColumnOriginalValue("reviewId"));
		reviewUploadImpl.setAttachmentName(
			this.<String>getColumnOriginalValue("attachmentName"));
		reviewUploadImpl.setFileId(
			this.<String>getColumnOriginalValue("fileId"));
		reviewUploadImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("createdDate"));

		return reviewUploadImpl;
	}

	@Override
	public int compareTo(ReviewUpload reviewUpload) {
		long primaryKey = reviewUpload.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReviewUpload)) {
			return false;
		}

		ReviewUpload reviewUpload = (ReviewUpload)object;

		long primaryKey = reviewUpload.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReviewUpload> toCacheModel() {
		ReviewUploadCacheModel reviewUploadCacheModel =
			new ReviewUploadCacheModel();

		reviewUploadCacheModel.uploadId = getUploadId();

		reviewUploadCacheModel.reviewId = getReviewId();

		reviewUploadCacheModel.attachmentName = getAttachmentName();

		String attachmentName = reviewUploadCacheModel.attachmentName;

		if ((attachmentName != null) && (attachmentName.length() == 0)) {
			reviewUploadCacheModel.attachmentName = null;
		}

		reviewUploadCacheModel.fileId = getFileId();

		String fileId = reviewUploadCacheModel.fileId;

		if ((fileId != null) && (fileId.length() == 0)) {
			reviewUploadCacheModel.fileId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			reviewUploadCacheModel.createdDate = createdDate.getTime();
		}
		else {
			reviewUploadCacheModel.createdDate = Long.MIN_VALUE;
		}

		return reviewUploadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReviewUpload, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReviewUpload, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewUpload, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReviewUpload)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReviewUpload>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReviewUpload.class, ModelWrapper.class);

	}

	private long _uploadId;
	private long _reviewId;
	private String _attachmentName;
	private String _fileId;
	private Date _createdDate;

	public <T> T getColumnValue(String columnName) {
		Function<ReviewUpload, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReviewUpload)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uploadId", _uploadId);
		_columnOriginalValues.put("reviewId", _reviewId);
		_columnOriginalValues.put("attachmentName", _attachmentName);
		_columnOriginalValues.put("fileId", _fileId);
		_columnOriginalValues.put("createdDate", _createdDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uploadId", 1L);

		columnBitmasks.put("reviewId", 2L);

		columnBitmasks.put("attachmentName", 4L);

		columnBitmasks.put("fileId", 8L);

		columnBitmasks.put("createdDate", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReviewUpload _escapedModel;

}