/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.ReviewTimeline;
import com.trantorinc.synergy.performance.core.model.ReviewTimelineModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReviewTimeline service. Represents a row in the &quot;PERFORMANCE_ReviewTimeline&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReviewTimelineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewTimelineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewTimelineImpl
 * @generated
 */
public class ReviewTimelineModelImpl
	extends BaseModelImpl<ReviewTimeline> implements ReviewTimelineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a review timeline model instance should use the <code>ReviewTimeline</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_ReviewTimeline";

	public static final Object[][] TABLE_COLUMNS = {
		{"timelineId", Types.BIGINT}, {"reviewState", Types.INTEGER},
		{"stateName", Types.VARCHAR}, {"endDate", Types.TIMESTAMP},
		{"finalYear", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("timelineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewState", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("stateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("finalYear", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_ReviewTimeline (timelineId LONG not null primary key,reviewState INTEGER,stateName VARCHAR(75) null,endDate DATE null,finalYear BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_ReviewTimeline";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reviewTimeline.timelineId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_ReviewTimeline.timelineId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIMELINEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReviewTimelineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _timelineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTimelineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _timelineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReviewTimeline.class;
	}

	@Override
	public String getModelClassName() {
		return ReviewTimeline.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReviewTimeline, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReviewTimeline, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewTimeline, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReviewTimeline)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReviewTimeline, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReviewTimeline, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReviewTimeline)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReviewTimeline, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReviewTimeline, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReviewTimeline, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReviewTimeline, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReviewTimeline, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReviewTimeline, Object>>();
		Map<String, BiConsumer<ReviewTimeline, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReviewTimeline, ?>>();

		attributeGetterFunctions.put(
			"timelineId", ReviewTimeline::getTimelineId);
		attributeSetterBiConsumers.put(
			"timelineId",
			(BiConsumer<ReviewTimeline, Long>)ReviewTimeline::setTimelineId);
		attributeGetterFunctions.put(
			"reviewState", ReviewTimeline::getReviewState);
		attributeSetterBiConsumers.put(
			"reviewState",
			(BiConsumer<ReviewTimeline, Integer>)
				ReviewTimeline::setReviewState);
		attributeGetterFunctions.put("stateName", ReviewTimeline::getStateName);
		attributeSetterBiConsumers.put(
			"stateName",
			(BiConsumer<ReviewTimeline, String>)ReviewTimeline::setStateName);
		attributeGetterFunctions.put("endDate", ReviewTimeline::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate",
			(BiConsumer<ReviewTimeline, Date>)ReviewTimeline::setEndDate);
		attributeGetterFunctions.put("finalYear", ReviewTimeline::getFinalYear);
		attributeSetterBiConsumers.put(
			"finalYear",
			(BiConsumer<ReviewTimeline, Boolean>)ReviewTimeline::setFinalYear);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTimelineId() {
		return _timelineId;
	}

	@Override
	public void setTimelineId(long timelineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timelineId = timelineId;
	}

	@Override
	public int getReviewState() {
		return _reviewState;
	}

	@Override
	public void setReviewState(int reviewState) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewState = reviewState;
	}

	@Override
	public String getStateName() {
		if (_stateName == null) {
			return "";
		}
		else {
			return _stateName;
		}
	}

	@Override
	public void setStateName(String stateName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateName = stateName;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@Override
	public boolean getFinalYear() {
		return _finalYear;
	}

	@Override
	public boolean isFinalYear() {
		return _finalYear;
	}

	@Override
	public void setFinalYear(boolean finalYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_finalYear = finalYear;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReviewTimeline.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReviewTimeline toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReviewTimeline>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReviewTimelineImpl reviewTimelineImpl = new ReviewTimelineImpl();

		reviewTimelineImpl.setTimelineId(getTimelineId());
		reviewTimelineImpl.setReviewState(getReviewState());
		reviewTimelineImpl.setStateName(getStateName());
		reviewTimelineImpl.setEndDate(getEndDate());
		reviewTimelineImpl.setFinalYear(isFinalYear());

		reviewTimelineImpl.resetOriginalValues();

		return reviewTimelineImpl;
	}

	@Override
	public ReviewTimeline cloneWithOriginalValues() {
		ReviewTimelineImpl reviewTimelineImpl = new ReviewTimelineImpl();

		reviewTimelineImpl.setTimelineId(
			this.<Long>getColumnOriginalValue("timelineId"));
		reviewTimelineImpl.setReviewState(
			this.<Integer>getColumnOriginalValue("reviewState"));
		reviewTimelineImpl.setStateName(
			this.<String>getColumnOriginalValue("stateName"));
		reviewTimelineImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		reviewTimelineImpl.setFinalYear(
			this.<Boolean>getColumnOriginalValue("finalYear"));

		return reviewTimelineImpl;
	}

	@Override
	public int compareTo(ReviewTimeline reviewTimeline) {
		long primaryKey = reviewTimeline.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReviewTimeline)) {
			return false;
		}

		ReviewTimeline reviewTimeline = (ReviewTimeline)object;

		long primaryKey = reviewTimeline.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReviewTimeline> toCacheModel() {
		ReviewTimelineCacheModel reviewTimelineCacheModel =
			new ReviewTimelineCacheModel();

		reviewTimelineCacheModel.timelineId = getTimelineId();

		reviewTimelineCacheModel.reviewState = getReviewState();

		reviewTimelineCacheModel.stateName = getStateName();

		String stateName = reviewTimelineCacheModel.stateName;

		if ((stateName != null) && (stateName.length() == 0)) {
			reviewTimelineCacheModel.stateName = null;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			reviewTimelineCacheModel.endDate = endDate.getTime();
		}
		else {
			reviewTimelineCacheModel.endDate = Long.MIN_VALUE;
		}

		reviewTimelineCacheModel.finalYear = isFinalYear();

		return reviewTimelineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReviewTimeline, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReviewTimeline, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewTimeline, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReviewTimeline)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReviewTimeline>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReviewTimeline.class, ModelWrapper.class);

	}

	private long _timelineId;
	private int _reviewState;
	private String _stateName;
	private Date _endDate;
	private boolean _finalYear;

	public <T> T getColumnValue(String columnName) {
		Function<ReviewTimeline, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReviewTimeline)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("timelineId", _timelineId);
		_columnOriginalValues.put("reviewState", _reviewState);
		_columnOriginalValues.put("stateName", _stateName);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("finalYear", _finalYear);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("timelineId", 1L);

		columnBitmasks.put("reviewState", 2L);

		columnBitmasks.put("stateName", 4L);

		columnBitmasks.put("endDate", 8L);

		columnBitmasks.put("finalYear", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReviewTimeline _escapedModel;

}