/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.ReviewLine;
import com.trantorinc.synergy.performance.core.model.ReviewLineModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReviewLine service. Represents a row in the &quot;PERFORMANCE_ReviewLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReviewLineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewLineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewLineImpl
 * @generated
 */
public class ReviewLineModelImpl
	extends BaseModelImpl<ReviewLine> implements ReviewLineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a review line model instance should use the <code>ReviewLine</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_ReviewLine";

	public static final Object[][] TABLE_COLUMNS = {
		{"lineId", Types.BIGINT}, {"reviewId", Types.BIGINT},
		{"guideId", Types.BIGINT}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"target", Types.VARCHAR},
		{"employeeRating", Types.VARCHAR}, {"employeeComment", Types.VARCHAR},
		{"managerRating", Types.VARCHAR}, {"managerComment", Types.VARCHAR},
		{"hrRating", Types.VARCHAR}, {"hrComment", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("guideId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("target", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeRating", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managerRating", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managerComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hrRating", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hrComment", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_ReviewLine (lineId LONG not null primary key,reviewId LONG,guideId LONG,title VARCHAR(75) null,description TEXT null,target TEXT null,employeeRating VARCHAR(75) null,employeeComment TEXT null,managerRating VARCHAR(75) null,managerComment TEXT null,hrRating VARCHAR(75) null,hrComment TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_ReviewLine";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reviewLine.lineId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_ReviewLine.lineId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LINEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReviewLineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReviewLine.class;
	}

	@Override
	public String getModelClassName() {
		return ReviewLine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReviewLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReviewLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewLine, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ReviewLine)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReviewLine, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReviewLine, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReviewLine)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReviewLine, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReviewLine, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReviewLine, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReviewLine, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReviewLine, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReviewLine, Object>>();
		Map<String, BiConsumer<ReviewLine, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReviewLine, ?>>();

		attributeGetterFunctions.put("lineId", ReviewLine::getLineId);
		attributeSetterBiConsumers.put(
			"lineId", (BiConsumer<ReviewLine, Long>)ReviewLine::setLineId);
		attributeGetterFunctions.put("reviewId", ReviewLine::getReviewId);
		attributeSetterBiConsumers.put(
			"reviewId", (BiConsumer<ReviewLine, Long>)ReviewLine::setReviewId);
		attributeGetterFunctions.put("guideId", ReviewLine::getGuideId);
		attributeSetterBiConsumers.put(
			"guideId", (BiConsumer<ReviewLine, Long>)ReviewLine::setGuideId);
		attributeGetterFunctions.put("title", ReviewLine::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<ReviewLine, String>)ReviewLine::setTitle);
		attributeGetterFunctions.put("description", ReviewLine::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ReviewLine, String>)ReviewLine::setDescription);
		attributeGetterFunctions.put("target", ReviewLine::getTarget);
		attributeSetterBiConsumers.put(
			"target", (BiConsumer<ReviewLine, String>)ReviewLine::setTarget);
		attributeGetterFunctions.put(
			"employeeRating", ReviewLine::getEmployeeRating);
		attributeSetterBiConsumers.put(
			"employeeRating",
			(BiConsumer<ReviewLine, String>)ReviewLine::setEmployeeRating);
		attributeGetterFunctions.put(
			"employeeComment", ReviewLine::getEmployeeComment);
		attributeSetterBiConsumers.put(
			"employeeComment",
			(BiConsumer<ReviewLine, String>)ReviewLine::setEmployeeComment);
		attributeGetterFunctions.put(
			"managerRating", ReviewLine::getManagerRating);
		attributeSetterBiConsumers.put(
			"managerRating",
			(BiConsumer<ReviewLine, String>)ReviewLine::setManagerRating);
		attributeGetterFunctions.put(
			"managerComment", ReviewLine::getManagerComment);
		attributeSetterBiConsumers.put(
			"managerComment",
			(BiConsumer<ReviewLine, String>)ReviewLine::setManagerComment);
		attributeGetterFunctions.put("hrRating", ReviewLine::getHrRating);
		attributeSetterBiConsumers.put(
			"hrRating",
			(BiConsumer<ReviewLine, String>)ReviewLine::setHrRating);
		attributeGetterFunctions.put("hrComment", ReviewLine::getHrComment);
		attributeSetterBiConsumers.put(
			"hrComment",
			(BiConsumer<ReviewLine, String>)ReviewLine::setHrComment);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLineId() {
		return _lineId;
	}

	@Override
	public void setLineId(long lineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lineId = lineId;
	}

	@Override
	public long getReviewId() {
		return _reviewId;
	}

	@Override
	public void setReviewId(long reviewId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewId = reviewId;
	}

	@Override
	public long getGuideId() {
		return _guideId;
	}

	@Override
	public void setGuideId(long guideId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_guideId = guideId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getTarget() {
		if (_target == null) {
			return "";
		}
		else {
			return _target;
		}
	}

	@Override
	public void setTarget(String target) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_target = target;
	}

	@Override
	public String getEmployeeRating() {
		if (_employeeRating == null) {
			return "";
		}
		else {
			return _employeeRating;
		}
	}

	@Override
	public void setEmployeeRating(String employeeRating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeRating = employeeRating;
	}

	@Override
	public String getEmployeeComment() {
		if (_employeeComment == null) {
			return "";
		}
		else {
			return _employeeComment;
		}
	}

	@Override
	public void setEmployeeComment(String employeeComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeComment = employeeComment;
	}

	@Override
	public String getManagerRating() {
		if (_managerRating == null) {
			return "";
		}
		else {
			return _managerRating;
		}
	}

	@Override
	public void setManagerRating(String managerRating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerRating = managerRating;
	}

	@Override
	public String getManagerComment() {
		if (_managerComment == null) {
			return "";
		}
		else {
			return _managerComment;
		}
	}

	@Override
	public void setManagerComment(String managerComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerComment = managerComment;
	}

	@Override
	public String getHrRating() {
		if (_hrRating == null) {
			return "";
		}
		else {
			return _hrRating;
		}
	}

	@Override
	public void setHrRating(String hrRating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hrRating = hrRating;
	}

	@Override
	public String getHrComment() {
		if (_hrComment == null) {
			return "";
		}
		else {
			return _hrComment;
		}
	}

	@Override
	public void setHrComment(String hrComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hrComment = hrComment;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReviewLine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReviewLine toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReviewLine>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReviewLineImpl reviewLineImpl = new ReviewLineImpl();

		reviewLineImpl.setLineId(getLineId());
		reviewLineImpl.setReviewId(getReviewId());
		reviewLineImpl.setGuideId(getGuideId());
		reviewLineImpl.setTitle(getTitle());
		reviewLineImpl.setDescription(getDescription());
		reviewLineImpl.setTarget(getTarget());
		reviewLineImpl.setEmployeeRating(getEmployeeRating());
		reviewLineImpl.setEmployeeComment(getEmployeeComment());
		reviewLineImpl.setManagerRating(getManagerRating());
		reviewLineImpl.setManagerComment(getManagerComment());
		reviewLineImpl.setHrRating(getHrRating());
		reviewLineImpl.setHrComment(getHrComment());

		reviewLineImpl.resetOriginalValues();

		return reviewLineImpl;
	}

	@Override
	public ReviewLine cloneWithOriginalValues() {
		ReviewLineImpl reviewLineImpl = new ReviewLineImpl();

		reviewLineImpl.setLineId(this.<Long>getColumnOriginalValue("lineId"));
		reviewLineImpl.setReviewId(
			this.<Long>getColumnOriginalValue("reviewId"));
		reviewLineImpl.setGuideId(this.<Long>getColumnOriginalValue("guideId"));
		reviewLineImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		reviewLineImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		reviewLineImpl.setTarget(this.<String>getColumnOriginalValue("target"));
		reviewLineImpl.setEmployeeRating(
			this.<String>getColumnOriginalValue("employeeRating"));
		reviewLineImpl.setEmployeeComment(
			this.<String>getColumnOriginalValue("employeeComment"));
		reviewLineImpl.setManagerRating(
			this.<String>getColumnOriginalValue("managerRating"));
		reviewLineImpl.setManagerComment(
			this.<String>getColumnOriginalValue("managerComment"));
		reviewLineImpl.setHrRating(
			this.<String>getColumnOriginalValue("hrRating"));
		reviewLineImpl.setHrComment(
			this.<String>getColumnOriginalValue("hrComment"));

		return reviewLineImpl;
	}

	@Override
	public int compareTo(ReviewLine reviewLine) {
		long primaryKey = reviewLine.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReviewLine)) {
			return false;
		}

		ReviewLine reviewLine = (ReviewLine)object;

		long primaryKey = reviewLine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReviewLine> toCacheModel() {
		ReviewLineCacheModel reviewLineCacheModel = new ReviewLineCacheModel();

		reviewLineCacheModel.lineId = getLineId();

		reviewLineCacheModel.reviewId = getReviewId();

		reviewLineCacheModel.guideId = getGuideId();

		reviewLineCacheModel.title = getTitle();

		String title = reviewLineCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			reviewLineCacheModel.title = null;
		}

		reviewLineCacheModel.description = getDescription();

		String description = reviewLineCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			reviewLineCacheModel.description = null;
		}

		reviewLineCacheModel.target = getTarget();

		String target = reviewLineCacheModel.target;

		if ((target != null) && (target.length() == 0)) {
			reviewLineCacheModel.target = null;
		}

		reviewLineCacheModel.employeeRating = getEmployeeRating();

		String employeeRating = reviewLineCacheModel.employeeRating;

		if ((employeeRating != null) && (employeeRating.length() == 0)) {
			reviewLineCacheModel.employeeRating = null;
		}

		reviewLineCacheModel.employeeComment = getEmployeeComment();

		String employeeComment = reviewLineCacheModel.employeeComment;

		if ((employeeComment != null) && (employeeComment.length() == 0)) {
			reviewLineCacheModel.employeeComment = null;
		}

		reviewLineCacheModel.managerRating = getManagerRating();

		String managerRating = reviewLineCacheModel.managerRating;

		if ((managerRating != null) && (managerRating.length() == 0)) {
			reviewLineCacheModel.managerRating = null;
		}

		reviewLineCacheModel.managerComment = getManagerComment();

		String managerComment = reviewLineCacheModel.managerComment;

		if ((managerComment != null) && (managerComment.length() == 0)) {
			reviewLineCacheModel.managerComment = null;
		}

		reviewLineCacheModel.hrRating = getHrRating();

		String hrRating = reviewLineCacheModel.hrRating;

		if ((hrRating != null) && (hrRating.length() == 0)) {
			reviewLineCacheModel.hrRating = null;
		}

		reviewLineCacheModel.hrComment = getHrComment();

		String hrComment = reviewLineCacheModel.hrComment;

		if ((hrComment != null) && (hrComment.length() == 0)) {
			reviewLineCacheModel.hrComment = null;
		}

		return reviewLineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReviewLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReviewLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewLine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReviewLine)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReviewLine>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReviewLine.class, ModelWrapper.class);

	}

	private long _lineId;
	private long _reviewId;
	private long _guideId;
	private String _title;
	private String _description;
	private String _target;
	private String _employeeRating;
	private String _employeeComment;
	private String _managerRating;
	private String _managerComment;
	private String _hrRating;
	private String _hrComment;

	public <T> T getColumnValue(String columnName) {
		Function<ReviewLine, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReviewLine)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("lineId", _lineId);
		_columnOriginalValues.put("reviewId", _reviewId);
		_columnOriginalValues.put("guideId", _guideId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("target", _target);
		_columnOriginalValues.put("employeeRating", _employeeRating);
		_columnOriginalValues.put("employeeComment", _employeeComment);
		_columnOriginalValues.put("managerRating", _managerRating);
		_columnOriginalValues.put("managerComment", _managerComment);
		_columnOriginalValues.put("hrRating", _hrRating);
		_columnOriginalValues.put("hrComment", _hrComment);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("lineId", 1L);

		columnBitmasks.put("reviewId", 2L);

		columnBitmasks.put("guideId", 4L);

		columnBitmasks.put("title", 8L);

		columnBitmasks.put("description", 16L);

		columnBitmasks.put("target", 32L);

		columnBitmasks.put("employeeRating", 64L);

		columnBitmasks.put("employeeComment", 128L);

		columnBitmasks.put("managerRating", 256L);

		columnBitmasks.put("managerComment", 512L);

		columnBitmasks.put("hrRating", 1024L);

		columnBitmasks.put("hrComment", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReviewLine _escapedModel;

}