/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.performance.core.model.ReviewClose;
import com.trantorinc.synergy.performance.core.model.ReviewCloseModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReviewClose service. Represents a row in the &quot;PERFORMANCE_ReviewClose&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReviewCloseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReviewCloseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewCloseImpl
 * @generated
 */
public class ReviewCloseModelImpl
	extends BaseModelImpl<ReviewClose> implements ReviewCloseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a review close model instance should use the <code>ReviewClose</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERFORMANCE_ReviewClose";

	public static final Object[][] TABLE_COLUMNS = {
		{"closeId", Types.BIGINT}, {"reviewId", Types.BIGINT},
		{"requestBy", Types.VARCHAR}, {"requestDate", Types.TIMESTAMP},
		{"actionDate", Types.TIMESTAMP}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("closeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("actionDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERFORMANCE_ReviewClose (closeId LONG not null primary key,reviewId LONG,requestBy VARCHAR(75) null,requestDate DATE null,actionDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table PERFORMANCE_ReviewClose";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reviewClose.closeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PERFORMANCE_ReviewClose.closeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLOSEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReviewCloseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _closeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCloseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _closeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReviewClose.class;
	}

	@Override
	public String getModelClassName() {
		return ReviewClose.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReviewClose, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReviewClose, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewClose, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReviewClose)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReviewClose, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReviewClose, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReviewClose)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReviewClose, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReviewClose, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReviewClose, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReviewClose, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReviewClose, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReviewClose, Object>>();
		Map<String, BiConsumer<ReviewClose, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReviewClose, ?>>();

		attributeGetterFunctions.put("closeId", ReviewClose::getCloseId);
		attributeSetterBiConsumers.put(
			"closeId", (BiConsumer<ReviewClose, Long>)ReviewClose::setCloseId);
		attributeGetterFunctions.put("reviewId", ReviewClose::getReviewId);
		attributeSetterBiConsumers.put(
			"reviewId",
			(BiConsumer<ReviewClose, Long>)ReviewClose::setReviewId);
		attributeGetterFunctions.put("requestBy", ReviewClose::getRequestBy);
		attributeSetterBiConsumers.put(
			"requestBy",
			(BiConsumer<ReviewClose, String>)ReviewClose::setRequestBy);
		attributeGetterFunctions.put(
			"requestDate", ReviewClose::getRequestDate);
		attributeSetterBiConsumers.put(
			"requestDate",
			(BiConsumer<ReviewClose, Date>)ReviewClose::setRequestDate);
		attributeGetterFunctions.put("actionDate", ReviewClose::getActionDate);
		attributeSetterBiConsumers.put(
			"actionDate",
			(BiConsumer<ReviewClose, Date>)ReviewClose::setActionDate);
		attributeGetterFunctions.put("status", ReviewClose::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<ReviewClose, Integer>)ReviewClose::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCloseId() {
		return _closeId;
	}

	@Override
	public void setCloseId(long closeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_closeId = closeId;
	}

	@Override
	public long getReviewId() {
		return _reviewId;
	}

	@Override
	public void setReviewId(long reviewId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewId = reviewId;
	}

	@Override
	public String getRequestBy() {
		if (_requestBy == null) {
			return "";
		}
		else {
			return _requestBy;
		}
	}

	@Override
	public void setRequestBy(String requestBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestBy = requestBy;
	}

	@Override
	public Date getRequestDate() {
		return _requestDate;
	}

	@Override
	public void setRequestDate(Date requestDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestDate = requestDate;
	}

	@Override
	public Date getActionDate() {
		return _actionDate;
	}

	@Override
	public void setActionDate(Date actionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actionDate = actionDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReviewClose.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReviewClose toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReviewClose>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReviewCloseImpl reviewCloseImpl = new ReviewCloseImpl();

		reviewCloseImpl.setCloseId(getCloseId());
		reviewCloseImpl.setReviewId(getReviewId());
		reviewCloseImpl.setRequestBy(getRequestBy());
		reviewCloseImpl.setRequestDate(getRequestDate());
		reviewCloseImpl.setActionDate(getActionDate());
		reviewCloseImpl.setStatus(getStatus());

		reviewCloseImpl.resetOriginalValues();

		return reviewCloseImpl;
	}

	@Override
	public ReviewClose cloneWithOriginalValues() {
		ReviewCloseImpl reviewCloseImpl = new ReviewCloseImpl();

		reviewCloseImpl.setCloseId(
			this.<Long>getColumnOriginalValue("closeId"));
		reviewCloseImpl.setReviewId(
			this.<Long>getColumnOriginalValue("reviewId"));
		reviewCloseImpl.setRequestBy(
			this.<String>getColumnOriginalValue("requestBy"));
		reviewCloseImpl.setRequestDate(
			this.<Date>getColumnOriginalValue("requestDate"));
		reviewCloseImpl.setActionDate(
			this.<Date>getColumnOriginalValue("actionDate"));
		reviewCloseImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));

		return reviewCloseImpl;
	}

	@Override
	public int compareTo(ReviewClose reviewClose) {
		long primaryKey = reviewClose.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReviewClose)) {
			return false;
		}

		ReviewClose reviewClose = (ReviewClose)object;

		long primaryKey = reviewClose.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReviewClose> toCacheModel() {
		ReviewCloseCacheModel reviewCloseCacheModel =
			new ReviewCloseCacheModel();

		reviewCloseCacheModel.closeId = getCloseId();

		reviewCloseCacheModel.reviewId = getReviewId();

		reviewCloseCacheModel.requestBy = getRequestBy();

		String requestBy = reviewCloseCacheModel.requestBy;

		if ((requestBy != null) && (requestBy.length() == 0)) {
			reviewCloseCacheModel.requestBy = null;
		}

		Date requestDate = getRequestDate();

		if (requestDate != null) {
			reviewCloseCacheModel.requestDate = requestDate.getTime();
		}
		else {
			reviewCloseCacheModel.requestDate = Long.MIN_VALUE;
		}

		Date actionDate = getActionDate();

		if (actionDate != null) {
			reviewCloseCacheModel.actionDate = actionDate.getTime();
		}
		else {
			reviewCloseCacheModel.actionDate = Long.MIN_VALUE;
		}

		reviewCloseCacheModel.status = getStatus();

		return reviewCloseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReviewClose, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReviewClose, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReviewClose, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReviewClose)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReviewClose>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReviewClose.class, ModelWrapper.class);

	}

	private long _closeId;
	private long _reviewId;
	private String _requestBy;
	private Date _requestDate;
	private Date _actionDate;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		Function<ReviewClose, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReviewClose)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("closeId", _closeId);
		_columnOriginalValues.put("reviewId", _reviewId);
		_columnOriginalValues.put("requestBy", _requestBy);
		_columnOriginalValues.put("requestDate", _requestDate);
		_columnOriginalValues.put("actionDate", _actionDate);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("closeId", 1L);

		columnBitmasks.put("reviewId", 2L);

		columnBitmasks.put("requestBy", 4L);

		columnBitmasks.put("requestDate", 8L);

		columnBitmasks.put("actionDate", 16L);

		columnBitmasks.put("status", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReviewClose _escapedModel;

}