/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.expense.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.expense.core.model.ExpenseLine;
import com.trantorinc.synergy.expense.core.model.ExpenseLineModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExpenseLine service. Represents a row in the &quot;EXPENSE_ExpenseLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExpenseLineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpenseLineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExpenseLineImpl
 * @generated
 */
public class ExpenseLineModelImpl
	extends BaseModelImpl<ExpenseLine> implements ExpenseLineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a expense line model instance should use the <code>ExpenseLine</code> interface instead.
	 */
	public static final String TABLE_NAME = "EXPENSE_ExpenseLine";

	public static final Object[][] TABLE_COLUMNS = {
		{"lineId", Types.BIGINT}, {"expenseId", Types.BIGINT},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"description", Types.VARCHAR}, {"billAmount", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("expenseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("billAmount", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EXPENSE_ExpenseLine (lineId LONG not null primary key,expenseId LONG,startDate DATE null,endDate DATE null,description VARCHAR(1000) null,billAmount LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table EXPENSE_ExpenseLine";

	public static final String ORDER_BY_JPQL =
		" ORDER BY expenseLine.expenseId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EXPENSE_ExpenseLine.expenseId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPENSEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ExpenseLineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExpenseLine.class;
	}

	@Override
	public String getModelClassName() {
		return ExpenseLine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExpenseLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExpenseLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExpenseLine, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ExpenseLine)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExpenseLine, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExpenseLine, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExpenseLine)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExpenseLine, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExpenseLine, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ExpenseLine, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ExpenseLine, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ExpenseLine, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ExpenseLine, Object>>();
		Map<String, BiConsumer<ExpenseLine, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ExpenseLine, ?>>();

		attributeGetterFunctions.put("lineId", ExpenseLine::getLineId);
		attributeSetterBiConsumers.put(
			"lineId", (BiConsumer<ExpenseLine, Long>)ExpenseLine::setLineId);
		attributeGetterFunctions.put("expenseId", ExpenseLine::getExpenseId);
		attributeSetterBiConsumers.put(
			"expenseId",
			(BiConsumer<ExpenseLine, Long>)ExpenseLine::setExpenseId);
		attributeGetterFunctions.put("startDate", ExpenseLine::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<ExpenseLine, Date>)ExpenseLine::setStartDate);
		attributeGetterFunctions.put("endDate", ExpenseLine::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate", (BiConsumer<ExpenseLine, Date>)ExpenseLine::setEndDate);
		attributeGetterFunctions.put(
			"description", ExpenseLine::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ExpenseLine, String>)ExpenseLine::setDescription);
		attributeGetterFunctions.put("billAmount", ExpenseLine::getBillAmount);
		attributeSetterBiConsumers.put(
			"billAmount",
			(BiConsumer<ExpenseLine, Long>)ExpenseLine::setBillAmount);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLineId() {
		return _lineId;
	}

	@Override
	public void setLineId(long lineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lineId = lineId;
	}

	@Override
	public long getExpenseId() {
		return _expenseId;
	}

	@Override
	public void setExpenseId(long expenseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expenseId = expenseId;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public long getBillAmount() {
		return _billAmount;
	}

	@Override
	public void setBillAmount(long billAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_billAmount = billAmount;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ExpenseLine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExpenseLine toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExpenseLine>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExpenseLineImpl expenseLineImpl = new ExpenseLineImpl();

		expenseLineImpl.setLineId(getLineId());
		expenseLineImpl.setExpenseId(getExpenseId());
		expenseLineImpl.setStartDate(getStartDate());
		expenseLineImpl.setEndDate(getEndDate());
		expenseLineImpl.setDescription(getDescription());
		expenseLineImpl.setBillAmount(getBillAmount());

		expenseLineImpl.resetOriginalValues();

		return expenseLineImpl;
	}

	@Override
	public ExpenseLine cloneWithOriginalValues() {
		ExpenseLineImpl expenseLineImpl = new ExpenseLineImpl();

		expenseLineImpl.setLineId(this.<Long>getColumnOriginalValue("lineId"));
		expenseLineImpl.setExpenseId(
			this.<Long>getColumnOriginalValue("expenseId"));
		expenseLineImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		expenseLineImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		expenseLineImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		expenseLineImpl.setBillAmount(
			this.<Long>getColumnOriginalValue("billAmount"));

		return expenseLineImpl;
	}

	@Override
	public int compareTo(ExpenseLine expenseLine) {
		int value = 0;

		if (getExpenseId() < expenseLine.getExpenseId()) {
			value = -1;
		}
		else if (getExpenseId() > expenseLine.getExpenseId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExpenseLine)) {
			return false;
		}

		ExpenseLine expenseLine = (ExpenseLine)object;

		long primaryKey = expenseLine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExpenseLine> toCacheModel() {
		ExpenseLineCacheModel expenseLineCacheModel =
			new ExpenseLineCacheModel();

		expenseLineCacheModel.lineId = getLineId();

		expenseLineCacheModel.expenseId = getExpenseId();

		Date startDate = getStartDate();

		if (startDate != null) {
			expenseLineCacheModel.startDate = startDate.getTime();
		}
		else {
			expenseLineCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			expenseLineCacheModel.endDate = endDate.getTime();
		}
		else {
			expenseLineCacheModel.endDate = Long.MIN_VALUE;
		}

		expenseLineCacheModel.description = getDescription();

		String description = expenseLineCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			expenseLineCacheModel.description = null;
		}

		expenseLineCacheModel.billAmount = getBillAmount();

		return expenseLineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExpenseLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExpenseLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExpenseLine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ExpenseLine)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ExpenseLine>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ExpenseLine.class, ModelWrapper.class);

	}

	private long _lineId;
	private long _expenseId;
	private Date _startDate;
	private Date _endDate;
	private String _description;
	private long _billAmount;

	public <T> T getColumnValue(String columnName) {
		Function<ExpenseLine, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ExpenseLine)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("lineId", _lineId);
		_columnOriginalValues.put("expenseId", _expenseId);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("billAmount", _billAmount);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("lineId", 1L);

		columnBitmasks.put("expenseId", 2L);

		columnBitmasks.put("startDate", 4L);

		columnBitmasks.put("endDate", 8L);

		columnBitmasks.put("description", 16L);

		columnBitmasks.put("billAmount", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ExpenseLine _escapedModel;

}