/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.notice.core.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.trantorinc.synergy.notice.core.model.ManagerForm;
import com.trantorinc.synergy.notice.core.service.ManagerFormLocalService;
import com.trantorinc.synergy.notice.core.service.ManagerFormLocalServiceUtil;
import com.trantorinc.synergy.notice.core.service.persistence.AdminFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.AdminFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ExitFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ExitFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ExitStatePersistence;
import com.trantorinc.synergy.notice.core.service.persistence.FinanceFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.FinanceFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.HrFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.HrFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ItFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ItFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ManagerFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ManagerFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.QuestionnaireFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.QuestionnaireFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.RecoveryReimbursementFinder;
import com.trantorinc.synergy.notice.core.service.persistence.RecoveryReimbursementPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ResignationFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ResignationPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the manager form local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.trantorinc.synergy.notice.core.service.impl.ManagerFormLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.trantorinc.synergy.notice.core.service.impl.ManagerFormLocalServiceImpl
 * @generated
 */
public abstract class ManagerFormLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, ManagerFormLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ManagerFormLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ManagerFormLocalServiceUtil</code>.
	 */

	/**
	 * Adds the manager form to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManagerFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param managerForm the manager form
	 * @return the manager form that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ManagerForm addManagerForm(ManagerForm managerForm) {
		managerForm.setNew(true);

		return managerFormPersistence.update(managerForm);
	}

	/**
	 * Creates a new manager form with the primary key. Does not add the manager form to the database.
	 *
	 * @param id the primary key for the new manager form
	 * @return the new manager form
	 */
	@Override
	@Transactional(enabled = false)
	public ManagerForm createManagerForm(long id) {
		return managerFormPersistence.create(id);
	}

	/**
	 * Deletes the manager form with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManagerFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the manager form
	 * @return the manager form that was removed
	 * @throws PortalException if a manager form with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ManagerForm deleteManagerForm(long id) throws PortalException {
		return managerFormPersistence.remove(id);
	}

	/**
	 * Deletes the manager form from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManagerFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param managerForm the manager form
	 * @return the manager form that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ManagerForm deleteManagerForm(ManagerForm managerForm) {
		return managerFormPersistence.remove(managerForm);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return managerFormPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ManagerForm.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return managerFormPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.ManagerFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return managerFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.ManagerFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return managerFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return managerFormPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return managerFormPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ManagerForm fetchManagerForm(long id) {
		return managerFormPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the manager form with the primary key.
	 *
	 * @param id the primary key of the manager form
	 * @return the manager form
	 * @throws PortalException if a manager form with the primary key could not be found
	 */
	@Override
	public ManagerForm getManagerForm(long id) throws PortalException {
		return managerFormPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(managerFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ManagerForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			managerFormLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ManagerForm.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(managerFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ManagerForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return managerFormPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ManagerFormLocalServiceImpl#deleteManagerForm(ManagerForm) to avoid orphaned data");
		}

		return managerFormLocalService.deleteManagerForm(
			(ManagerForm)persistedModel);
	}

	@Override
	public BasePersistence<ManagerForm> getBasePersistence() {
		return managerFormPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return managerFormPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the manager forms.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.ManagerFormModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of manager forms
	 * @param end the upper bound of the range of manager forms (not inclusive)
	 * @return the range of manager forms
	 */
	@Override
	public List<ManagerForm> getManagerForms(int start, int end) {
		return managerFormPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of manager forms.
	 *
	 * @return the number of manager forms
	 */
	@Override
	public int getManagerFormsCount() {
		return managerFormPersistence.countAll();
	}

	/**
	 * Updates the manager form in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ManagerFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param managerForm the manager form
	 * @return the manager form that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ManagerForm updateManagerForm(ManagerForm managerForm) {
		return managerFormPersistence.update(managerForm);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ManagerFormLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		managerFormLocalService = (ManagerFormLocalService)aopProxy;

		_setLocalServiceUtilService(managerFormLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ManagerFormLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ManagerForm.class;
	}

	protected String getModelClassName() {
		return ManagerForm.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = managerFormPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ManagerFormLocalService managerFormLocalService) {

		try {
			Field field = ManagerFormLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, managerFormLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AdminFormPersistence adminFormPersistence;

	@Reference
	protected AdminFormFinder adminFormFinder;

	@Reference
	protected ExitFormPersistence exitFormPersistence;

	@Reference
	protected ExitFormFinder exitFormFinder;

	@Reference
	protected ExitStatePersistence exitStatePersistence;

	@Reference
	protected FinanceFormPersistence financeFormPersistence;

	@Reference
	protected FinanceFormFinder financeFormFinder;

	@Reference
	protected HrFormPersistence hrFormPersistence;

	@Reference
	protected HrFormFinder hrFormFinder;

	@Reference
	protected ItFormPersistence itFormPersistence;

	@Reference
	protected ItFormFinder itFormFinder;

	protected ManagerFormLocalService managerFormLocalService;

	@Reference
	protected ManagerFormPersistence managerFormPersistence;

	@Reference
	protected ManagerFormFinder managerFormFinder;

	@Reference
	protected QuestionnaireFormPersistence questionnaireFormPersistence;

	@Reference
	protected QuestionnaireFormFinder questionnaireFormFinder;

	@Reference
	protected RecoveryReimbursementPersistence recoveryReimbursementPersistence;

	@Reference
	protected RecoveryReimbursementFinder recoveryReimbursementFinder;

	@Reference
	protected ResignationPersistence resignationPersistence;

	@Reference
	protected ResignationFinder resignationFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ManagerFormLocalServiceBaseImpl.class);

}