/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.notice.core.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.trantorinc.synergy.notice.core.model.QuestionnaireForm;
import com.trantorinc.synergy.notice.core.service.QuestionnaireFormLocalService;
import com.trantorinc.synergy.notice.core.service.QuestionnaireFormLocalServiceUtil;
import com.trantorinc.synergy.notice.core.service.persistence.AdminFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.AdminFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ExitFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ExitFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ExitStatePersistence;
import com.trantorinc.synergy.notice.core.service.persistence.FinanceFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.FinanceFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.HrFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.HrFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ItFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ItFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ManagerFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ManagerFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.QuestionnaireFormFinder;
import com.trantorinc.synergy.notice.core.service.persistence.QuestionnaireFormPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.RecoveryReimbursementFinder;
import com.trantorinc.synergy.notice.core.service.persistence.RecoveryReimbursementPersistence;
import com.trantorinc.synergy.notice.core.service.persistence.ResignationFinder;
import com.trantorinc.synergy.notice.core.service.persistence.ResignationPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the questionnaire form local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.trantorinc.synergy.notice.core.service.impl.QuestionnaireFormLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.trantorinc.synergy.notice.core.service.impl.QuestionnaireFormLocalServiceImpl
 * @generated
 */
public abstract class QuestionnaireFormLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   QuestionnaireFormLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>QuestionnaireFormLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>QuestionnaireFormLocalServiceUtil</code>.
	 */

	/**
	 * Adds the questionnaire form to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect QuestionnaireFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param questionnaireForm the questionnaire form
	 * @return the questionnaire form that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public QuestionnaireForm addQuestionnaireForm(
		QuestionnaireForm questionnaireForm) {

		questionnaireForm.setNew(true);

		return questionnaireFormPersistence.update(questionnaireForm);
	}

	/**
	 * Creates a new questionnaire form with the primary key. Does not add the questionnaire form to the database.
	 *
	 * @param id the primary key for the new questionnaire form
	 * @return the new questionnaire form
	 */
	@Override
	@Transactional(enabled = false)
	public QuestionnaireForm createQuestionnaireForm(long id) {
		return questionnaireFormPersistence.create(id);
	}

	/**
	 * Deletes the questionnaire form with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect QuestionnaireFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the questionnaire form
	 * @return the questionnaire form that was removed
	 * @throws PortalException if a questionnaire form with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public QuestionnaireForm deleteQuestionnaireForm(long id)
		throws PortalException {

		return questionnaireFormPersistence.remove(id);
	}

	/**
	 * Deletes the questionnaire form from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect QuestionnaireFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param questionnaireForm the questionnaire form
	 * @return the questionnaire form that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public QuestionnaireForm deleteQuestionnaireForm(
		QuestionnaireForm questionnaireForm) {

		return questionnaireFormPersistence.remove(questionnaireForm);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return questionnaireFormPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			QuestionnaireForm.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return questionnaireFormPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.QuestionnaireFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return questionnaireFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.QuestionnaireFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return questionnaireFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return questionnaireFormPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return questionnaireFormPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public QuestionnaireForm fetchQuestionnaireForm(long id) {
		return questionnaireFormPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the questionnaire form with the primary key.
	 *
	 * @param id the primary key of the questionnaire form
	 * @return the questionnaire form
	 * @throws PortalException if a questionnaire form with the primary key could not be found
	 */
	@Override
	public QuestionnaireForm getQuestionnaireForm(long id)
		throws PortalException {

		return questionnaireFormPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			questionnaireFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(QuestionnaireForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			questionnaireFormLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(QuestionnaireForm.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			questionnaireFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(QuestionnaireForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return questionnaireFormPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement QuestionnaireFormLocalServiceImpl#deleteQuestionnaireForm(QuestionnaireForm) to avoid orphaned data");
		}

		return questionnaireFormLocalService.deleteQuestionnaireForm(
			(QuestionnaireForm)persistedModel);
	}

	@Override
	public BasePersistence<QuestionnaireForm> getBasePersistence() {
		return questionnaireFormPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return questionnaireFormPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the questionnaire forms.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.notice.core.model.impl.QuestionnaireFormModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of questionnaire forms
	 * @param end the upper bound of the range of questionnaire forms (not inclusive)
	 * @return the range of questionnaire forms
	 */
	@Override
	public List<QuestionnaireForm> getQuestionnaireForms(int start, int end) {
		return questionnaireFormPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of questionnaire forms.
	 *
	 * @return the number of questionnaire forms
	 */
	@Override
	public int getQuestionnaireFormsCount() {
		return questionnaireFormPersistence.countAll();
	}

	/**
	 * Updates the questionnaire form in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect QuestionnaireFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param questionnaireForm the questionnaire form
	 * @return the questionnaire form that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public QuestionnaireForm updateQuestionnaireForm(
		QuestionnaireForm questionnaireForm) {

		return questionnaireFormPersistence.update(questionnaireForm);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			QuestionnaireFormLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		questionnaireFormLocalService = (QuestionnaireFormLocalService)aopProxy;

		_setLocalServiceUtilService(questionnaireFormLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return QuestionnaireFormLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return QuestionnaireForm.class;
	}

	protected String getModelClassName() {
		return QuestionnaireForm.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				questionnaireFormPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		QuestionnaireFormLocalService questionnaireFormLocalService) {

		try {
			Field field =
				QuestionnaireFormLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, questionnaireFormLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AdminFormPersistence adminFormPersistence;

	@Reference
	protected AdminFormFinder adminFormFinder;

	@Reference
	protected ExitFormPersistence exitFormPersistence;

	@Reference
	protected ExitFormFinder exitFormFinder;

	@Reference
	protected ExitStatePersistence exitStatePersistence;

	@Reference
	protected FinanceFormPersistence financeFormPersistence;

	@Reference
	protected FinanceFormFinder financeFormFinder;

	@Reference
	protected HrFormPersistence hrFormPersistence;

	@Reference
	protected HrFormFinder hrFormFinder;

	@Reference
	protected ItFormPersistence itFormPersistence;

	@Reference
	protected ItFormFinder itFormFinder;

	@Reference
	protected ManagerFormPersistence managerFormPersistence;

	@Reference
	protected ManagerFormFinder managerFormFinder;

	protected QuestionnaireFormLocalService questionnaireFormLocalService;

	@Reference
	protected QuestionnaireFormPersistence questionnaireFormPersistence;

	@Reference
	protected QuestionnaireFormFinder questionnaireFormFinder;

	@Reference
	protected RecoveryReimbursementPersistence recoveryReimbursementPersistence;

	@Reference
	protected RecoveryReimbursementFinder recoveryReimbursementFinder;

	@Reference
	protected ResignationPersistence resignationPersistence;

	@Reference
	protected ResignationFinder resignationFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		QuestionnaireFormLocalServiceBaseImpl.class);

}