package com.trantorinc.synergy.performance.web.constants;

import java.util.HashMap;
import java.util.Map;

/**
 * @author saurabh.kumar
 */
public class PerformanceWebPortletKeys {

	public static final String PERFORMANCEWEB =
		"com_trantorinc_synergy_performance_web_PerformanceWebPortlet";
	public static final String TO = " TO ";
	public static final String AY = "AY ";
	public static final String KPI_ID = "kpiId";
	public static final String YEAR_END_SMALL = "annual";
	public static final String MID_YEAR_SMALL = "mid-year";
	public static final String CONSISTENTLY_EXCEEDS_EXPECTATIONS = "Consistently Exceeds Expectations";
	public static final String SOMETIMES_EXCEEDS_EXPECTATIONS = "Sometimes Exceeds Expectations";
	public static final String CONSISTENTLY_MEETS_EXPECTATIONS = "Consistently Meets Expectations";
	public static final String INCONSISTENTLY_MEETS_EXPECTATIONS = "Inconsistently Meets Expectations";
	public static final String DOES_NOT_MEETS_EXPECTATIONS = "Does not Meet Expectations";
	public static final String SYSTEM_UPDATE = "systemupdate";
	public static final Integer GUIDEID_ZERO = 0;
	public static final String SUBJECT_MIDYEAR_SELF_REVIEW = "Mid-Year Performance Review - {1} has generated manager review form";
	public static final String BODY_MIDYEAR_SELF_REVIEW = "Dear Lead/Manager,<br><br>Manager Review form for employee \"{0}\" has been generated by employee and is ready for your review. If you are a lead doing review, please ensure that review forms are discussed with manager before submission.<br><br>Meeting with employee in Mid Year is optional.<br><br>Please <a href=''{1}''>click here</a> to start the review.<br><br>Regards,<br>Synergy Admin";

	public static final String SUBJECT_SUBMIT_KPIS = "Performance - KPIs submitted";
	public static final String BODY_SUBMIT_KPIS = "Dear Lead/Manager,<br><br>Employee \"{0}\" has submitted KPIs for Project \"{1}\". Kindly review and send back the KPIs if any changes are required.<br><br>In case, no changes are required then no action is required at your end.<br><br>Regards,<br>Synergy Admin";
	public static final String SUBJECT_RAISE_REQUEST_MEETING_TO_MANAGER = "Mid-Year Performance Review - Employee Meeting request";
	public static final String BODY_RAISE_REQUEST_MEETING_TO_MANAGER = "Dear Manager,<br><br>Employee \"{0}\" ({1}) from account \"{2}\" has raised request for Meeting on mid year review. Review has now been rolled back to  \"Manager Review Stage\". You are requested to meet employee, discuss and update form as needed and re-submit.<br><br>Please <a href=''{3}''>click here</a> for more information.<br><br>Regards,<br>Synergy Admin";
	public static final String SUBJECT_SELF_REVIEW = "Annual Performance Review - {0} has completed the Self Review";
	public static final String BODY_SELF_REVIEW = "Dear Lead/Manager,<br><br>Self Review for employee \"{0}\" has been completed and is ready for your review. If you are a lead doing review, please ensure that review forms are discussed with manager before meeting with employee for review meeting.<br>Please <a href=''{1}''>click here</a> to start the review.<br><br>Regards,<br>Synergy Admin";
	public static final String ANNUAL = "Annual";
	public static final String MID_YEAR = "Mid Year";
	public static final String SUBJECT_RAISETOHR = "{0} Performance Review - {1} ({2}) has raised to HR for {3} review";
	public static final String BODY_RAISETOHR = "Dear HR,<br><br>Employee  \"{0}\" ({1}) from account \"{2}\" has raised concerns on {3} review. Comments entered by employee are<br>\"{4}\"<br><br>Please <a href=''{5}''>click here</a> for more information.<br><br>Regards,<br>Synergy Admin";

}