/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.lms.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.lms.core.model.Holiday;
import com.trantorinc.synergy.lms.core.model.HolidayModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Holiday service. Represents a row in the &quot;LMS_Holiday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HolidayModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HolidayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HolidayImpl
 * @generated
 */
public class HolidayModelImpl
	extends BaseModelImpl<Holiday> implements HolidayModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a holiday model instance should use the <code>Holiday</code> interface instead.
	 */
	public static final String TABLE_NAME = "LMS_Holiday";

	public static final Object[][] TABLE_COLUMNS = {
		{"holidayId", Types.BIGINT}, {"holidayYear", Types.INTEGER},
		{"onDate", Types.TIMESTAMP}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("holidayId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("holidayYear", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("onDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LMS_Holiday (holidayId LONG not null primary key,holidayYear INTEGER,onDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LMS_Holiday";

	public static final String ORDER_BY_JPQL =
		" ORDER BY holiday.holidayId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LMS_Holiday.holidayId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HOLIDAYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public HolidayModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _holidayId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHolidayId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _holidayId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Holiday.class;
	}

	@Override
	public String getModelClassName() {
		return Holiday.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Holiday, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Holiday, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Holiday, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Holiday)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Holiday, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Holiday, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Holiday)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Holiday, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Holiday, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Holiday, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Holiday, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Holiday, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Holiday, Object>>();
		Map<String, BiConsumer<Holiday, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Holiday, ?>>();

		attributeGetterFunctions.put("holidayId", Holiday::getHolidayId);
		attributeSetterBiConsumers.put(
			"holidayId", (BiConsumer<Holiday, Long>)Holiday::setHolidayId);
		attributeGetterFunctions.put("holidayYear", Holiday::getHolidayYear);
		attributeSetterBiConsumers.put(
			"holidayYear",
			(BiConsumer<Holiday, Integer>)Holiday::setHolidayYear);
		attributeGetterFunctions.put("onDate", Holiday::getOnDate);
		attributeSetterBiConsumers.put(
			"onDate", (BiConsumer<Holiday, Date>)Holiday::setOnDate);
		attributeGetterFunctions.put("name", Holiday::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Holiday, String>)Holiday::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getHolidayId() {
		return _holidayId;
	}

	@Override
	public void setHolidayId(long holidayId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_holidayId = holidayId;
	}

	@Override
	public int getHolidayYear() {
		return _holidayYear;
	}

	@Override
	public void setHolidayYear(int holidayYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_holidayYear = holidayYear;
	}

	@Override
	public Date getOnDate() {
		return _onDate;
	}

	@Override
	public void setOnDate(Date onDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_onDate = onDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Holiday.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Holiday toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Holiday>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HolidayImpl holidayImpl = new HolidayImpl();

		holidayImpl.setHolidayId(getHolidayId());
		holidayImpl.setHolidayYear(getHolidayYear());
		holidayImpl.setOnDate(getOnDate());
		holidayImpl.setName(getName());

		holidayImpl.resetOriginalValues();

		return holidayImpl;
	}

	@Override
	public Holiday cloneWithOriginalValues() {
		HolidayImpl holidayImpl = new HolidayImpl();

		holidayImpl.setHolidayId(
			this.<Long>getColumnOriginalValue("holidayId"));
		holidayImpl.setHolidayYear(
			this.<Integer>getColumnOriginalValue("holidayYear"));
		holidayImpl.setOnDate(this.<Date>getColumnOriginalValue("onDate"));
		holidayImpl.setName(this.<String>getColumnOriginalValue("name"));

		return holidayImpl;
	}

	@Override
	public int compareTo(Holiday holiday) {
		long primaryKey = holiday.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Holiday)) {
			return false;
		}

		Holiday holiday = (Holiday)object;

		long primaryKey = holiday.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Holiday> toCacheModel() {
		HolidayCacheModel holidayCacheModel = new HolidayCacheModel();

		holidayCacheModel.holidayId = getHolidayId();

		holidayCacheModel.holidayYear = getHolidayYear();

		Date onDate = getOnDate();

		if (onDate != null) {
			holidayCacheModel.onDate = onDate.getTime();
		}
		else {
			holidayCacheModel.onDate = Long.MIN_VALUE;
		}

		holidayCacheModel.name = getName();

		String name = holidayCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			holidayCacheModel.name = null;
		}

		return holidayCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Holiday, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Holiday, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Holiday, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Holiday)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Holiday>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Holiday.class, ModelWrapper.class);

	}

	private long _holidayId;
	private int _holidayYear;
	private Date _onDate;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<Holiday, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Holiday)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("holidayId", _holidayId);
		_columnOriginalValues.put("holidayYear", _holidayYear);
		_columnOriginalValues.put("onDate", _onDate);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("holidayId", 1L);

		columnBitmasks.put("holidayYear", 2L);

		columnBitmasks.put("onDate", 4L);

		columnBitmasks.put("name", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Holiday _escapedModel;

}