/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.performance.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ReviewUpload service. Represents a row in the &quot;PERFORMANCE_ReviewUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.performance.core.model.impl.ReviewUploadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.performance.core.model.impl.ReviewUploadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReviewUpload
 * @generated
 */
@ProviderType
public interface ReviewUploadModel extends BaseModel<ReviewUpload> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a review upload model instance should use the {@link ReviewUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this review upload.
	 *
	 * @return the primary key of this review upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this review upload.
	 *
	 * @param primaryKey the primary key of this review upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the upload ID of this review upload.
	 *
	 * @return the upload ID of this review upload
	 */
	public long getUploadId();

	/**
	 * Sets the upload ID of this review upload.
	 *
	 * @param uploadId the upload ID of this review upload
	 */
	public void setUploadId(long uploadId);

	/**
	 * Returns the review ID of this review upload.
	 *
	 * @return the review ID of this review upload
	 */
	public long getReviewId();

	/**
	 * Sets the review ID of this review upload.
	 *
	 * @param reviewId the review ID of this review upload
	 */
	public void setReviewId(long reviewId);

	/**
	 * Returns the attachment name of this review upload.
	 *
	 * @return the attachment name of this review upload
	 */
	@AutoEscape
	public String getAttachmentName();

	/**
	 * Sets the attachment name of this review upload.
	 *
	 * @param attachmentName the attachment name of this review upload
	 */
	public void setAttachmentName(String attachmentName);

	/**
	 * Returns the file ID of this review upload.
	 *
	 * @return the file ID of this review upload
	 */
	@AutoEscape
	public String getFileId();

	/**
	 * Sets the file ID of this review upload.
	 *
	 * @param fileId the file ID of this review upload
	 */
	public void setFileId(String fileId);

	/**
	 * Returns the created date of this review upload.
	 *
	 * @return the created date of this review upload
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this review upload.
	 *
	 * @param createdDate the created date of this review upload
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public ReviewUpload cloneWithOriginalValues();

}