/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.notice.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.notice.core.model.ExitForm;
import com.trantorinc.synergy.notice.core.model.ExitFormModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExitForm service. Represents a row in the &quot;NOTICE_ExitForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExitFormModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExitFormImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExitFormImpl
 * @generated
 */
public class ExitFormModelImpl
	extends BaseModelImpl<ExitForm> implements ExitFormModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a exit form model instance should use the <code>ExitForm</code> interface instead.
	 */
	public static final String TABLE_NAME = "NOTICE_ExitForm";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"resignationId", Types.BIGINT},
		{"managerFormStatus", Types.BOOLEAN}, {"hrFormStatus", Types.BOOLEAN},
		{"itFormStatus", Types.BOOLEAN}, {"adminFormStatus", Types.BOOLEAN},
		{"financeFormStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resignationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("managerFormStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hrFormStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("itFormStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("adminFormStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("financeFormStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NOTICE_ExitForm (id_ LONG not null primary key,resignationId LONG,managerFormStatus BOOLEAN,hrFormStatus BOOLEAN,itFormStatus BOOLEAN,adminFormStatus BOOLEAN,financeFormStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table NOTICE_ExitForm";

	public static final String ORDER_BY_JPQL = " ORDER BY exitForm.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NOTICE_ExitForm.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ExitFormModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExitForm.class;
	}

	@Override
	public String getModelClassName() {
		return ExitForm.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExitForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExitForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExitForm, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ExitForm)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExitForm, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExitForm, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExitForm)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExitForm, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExitForm, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ExitForm, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ExitForm, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ExitForm, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ExitForm, Object>>();
		Map<String, BiConsumer<ExitForm, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ExitForm, ?>>();

		attributeGetterFunctions.put("id", ExitForm::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<ExitForm, Long>)ExitForm::setId);
		attributeGetterFunctions.put(
			"resignationId", ExitForm::getResignationId);
		attributeSetterBiConsumers.put(
			"resignationId",
			(BiConsumer<ExitForm, Long>)ExitForm::setResignationId);
		attributeGetterFunctions.put(
			"managerFormStatus", ExitForm::getManagerFormStatus);
		attributeSetterBiConsumers.put(
			"managerFormStatus",
			(BiConsumer<ExitForm, Boolean>)ExitForm::setManagerFormStatus);
		attributeGetterFunctions.put("hrFormStatus", ExitForm::getHrFormStatus);
		attributeSetterBiConsumers.put(
			"hrFormStatus",
			(BiConsumer<ExitForm, Boolean>)ExitForm::setHrFormStatus);
		attributeGetterFunctions.put("itFormStatus", ExitForm::getItFormStatus);
		attributeSetterBiConsumers.put(
			"itFormStatus",
			(BiConsumer<ExitForm, Boolean>)ExitForm::setItFormStatus);
		attributeGetterFunctions.put(
			"adminFormStatus", ExitForm::getAdminFormStatus);
		attributeSetterBiConsumers.put(
			"adminFormStatus",
			(BiConsumer<ExitForm, Boolean>)ExitForm::setAdminFormStatus);
		attributeGetterFunctions.put(
			"financeFormStatus", ExitForm::getFinanceFormStatus);
		attributeSetterBiConsumers.put(
			"financeFormStatus",
			(BiConsumer<ExitForm, Boolean>)ExitForm::setFinanceFormStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getResignationId() {
		return _resignationId;
	}

	@Override
	public void setResignationId(long resignationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resignationId = resignationId;
	}

	@Override
	public boolean getManagerFormStatus() {
		return _managerFormStatus;
	}

	@Override
	public boolean isManagerFormStatus() {
		return _managerFormStatus;
	}

	@Override
	public void setManagerFormStatus(boolean managerFormStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerFormStatus = managerFormStatus;
	}

	@Override
	public boolean getHrFormStatus() {
		return _hrFormStatus;
	}

	@Override
	public boolean isHrFormStatus() {
		return _hrFormStatus;
	}

	@Override
	public void setHrFormStatus(boolean hrFormStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hrFormStatus = hrFormStatus;
	}

	@Override
	public boolean getItFormStatus() {
		return _itFormStatus;
	}

	@Override
	public boolean isItFormStatus() {
		return _itFormStatus;
	}

	@Override
	public void setItFormStatus(boolean itFormStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itFormStatus = itFormStatus;
	}

	@Override
	public boolean getAdminFormStatus() {
		return _adminFormStatus;
	}

	@Override
	public boolean isAdminFormStatus() {
		return _adminFormStatus;
	}

	@Override
	public void setAdminFormStatus(boolean adminFormStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_adminFormStatus = adminFormStatus;
	}

	@Override
	public boolean getFinanceFormStatus() {
		return _financeFormStatus;
	}

	@Override
	public boolean isFinanceFormStatus() {
		return _financeFormStatus;
	}

	@Override
	public void setFinanceFormStatus(boolean financeFormStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_financeFormStatus = financeFormStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ExitForm.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExitForm toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExitForm>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExitFormImpl exitFormImpl = new ExitFormImpl();

		exitFormImpl.setId(getId());
		exitFormImpl.setResignationId(getResignationId());
		exitFormImpl.setManagerFormStatus(isManagerFormStatus());
		exitFormImpl.setHrFormStatus(isHrFormStatus());
		exitFormImpl.setItFormStatus(isItFormStatus());
		exitFormImpl.setAdminFormStatus(isAdminFormStatus());
		exitFormImpl.setFinanceFormStatus(isFinanceFormStatus());

		exitFormImpl.resetOriginalValues();

		return exitFormImpl;
	}

	@Override
	public ExitForm cloneWithOriginalValues() {
		ExitFormImpl exitFormImpl = new ExitFormImpl();

		exitFormImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		exitFormImpl.setResignationId(
			this.<Long>getColumnOriginalValue("resignationId"));
		exitFormImpl.setManagerFormStatus(
			this.<Boolean>getColumnOriginalValue("managerFormStatus"));
		exitFormImpl.setHrFormStatus(
			this.<Boolean>getColumnOriginalValue("hrFormStatus"));
		exitFormImpl.setItFormStatus(
			this.<Boolean>getColumnOriginalValue("itFormStatus"));
		exitFormImpl.setAdminFormStatus(
			this.<Boolean>getColumnOriginalValue("adminFormStatus"));
		exitFormImpl.setFinanceFormStatus(
			this.<Boolean>getColumnOriginalValue("financeFormStatus"));

		return exitFormImpl;
	}

	@Override
	public int compareTo(ExitForm exitForm) {
		long primaryKey = exitForm.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExitForm)) {
			return false;
		}

		ExitForm exitForm = (ExitForm)object;

		long primaryKey = exitForm.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExitForm> toCacheModel() {
		ExitFormCacheModel exitFormCacheModel = new ExitFormCacheModel();

		exitFormCacheModel.id = getId();

		exitFormCacheModel.resignationId = getResignationId();

		exitFormCacheModel.managerFormStatus = isManagerFormStatus();

		exitFormCacheModel.hrFormStatus = isHrFormStatus();

		exitFormCacheModel.itFormStatus = isItFormStatus();

		exitFormCacheModel.adminFormStatus = isAdminFormStatus();

		exitFormCacheModel.financeFormStatus = isFinanceFormStatus();

		return exitFormCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExitForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExitForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExitForm, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ExitForm)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ExitForm>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ExitForm.class, ModelWrapper.class);

	}

	private long _id;
	private long _resignationId;
	private boolean _managerFormStatus;
	private boolean _hrFormStatus;
	private boolean _itFormStatus;
	private boolean _adminFormStatus;
	private boolean _financeFormStatus;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ExitForm, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ExitForm)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("resignationId", _resignationId);
		_columnOriginalValues.put("managerFormStatus", _managerFormStatus);
		_columnOriginalValues.put("hrFormStatus", _hrFormStatus);
		_columnOriginalValues.put("itFormStatus", _itFormStatus);
		_columnOriginalValues.put("adminFormStatus", _adminFormStatus);
		_columnOriginalValues.put("financeFormStatus", _financeFormStatus);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("resignationId", 2L);

		columnBitmasks.put("managerFormStatus", 4L);

		columnBitmasks.put("hrFormStatus", 8L);

		columnBitmasks.put("itFormStatus", 16L);

		columnBitmasks.put("adminFormStatus", 32L);

		columnBitmasks.put("financeFormStatus", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ExitForm _escapedModel;

}