/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.notice.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.notice.core.model.FinanceForm;
import com.trantorinc.synergy.notice.core.model.FinanceFormModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FinanceForm service. Represents a row in the &quot;NOTICE_FinanceForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FinanceFormModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FinanceFormImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinanceFormImpl
 * @generated
 */
public class FinanceFormModelImpl
	extends BaseModelImpl<FinanceForm> implements FinanceFormModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a finance form model instance should use the <code>FinanceForm</code> interface instead.
	 */
	public static final String TABLE_NAME = "NOTICE_FinanceForm";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"exitId", Types.BIGINT},
		{"lastSalaryPaidDays", Types.BIGINT},
		{"lastSalaryPaidMonth", Types.VARCHAR},
		{"lastSalaryPaidYear", Types.VARCHAR},
		{"taxProofStatus", Types.INTEGER}, {"taxProofRemark", Types.VARCHAR},
		{"foodReimbursementStatus", Types.INTEGER},
		{"foodReimbursementAmt", Types.VARCHAR},
		{"travelRecoveryAmt", Types.VARCHAR},
		{"travelRecoveryStatus", Types.INTEGER},
		{"travelRecoveryApproved", Types.BOOLEAN},
		{"travelRecoveryComment", Types.VARCHAR},
		{"hotelRecoveryAmt", Types.VARCHAR},
		{"hotelRecoveryStatus", Types.INTEGER},
		{"hotelRecoveryApproved", Types.BOOLEAN},
		{"hotelRecoveryComment", Types.VARCHAR},
		{"internationalRecoveryAmt", Types.VARCHAR},
		{"internationalRecoveryStatus", Types.INTEGER},
		{"internationalRecoveryApproved", Types.BOOLEAN},
		{"internationalRecoveryComment", Types.VARCHAR},
		{"educationRecoveryAmt", Types.VARCHAR},
		{"educationRecoveryStatus", Types.INTEGER},
		{"educationRecoveryApproved", Types.BOOLEAN},
		{"educationRecoveryComment", Types.VARCHAR},
		{"joiningBonusRecoveryAmt", Types.VARCHAR},
		{"joiningBonusRecoveryStatus", Types.INTEGER},
		{"joiningRecoveryApproved", Types.BOOLEAN},
		{"joiningRecoveryComment", Types.VARCHAR},
		{"noticePeriodRecoveryAmt", Types.VARCHAR},
		{"noticePeriodRecoveryStatus", Types.INTEGER},
		{"noticePeriodRecoveryApproved", Types.BOOLEAN},
		{"noticePeriodRecoveryComment", Types.VARCHAR},
		{"updatedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("exitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lastSalaryPaidDays", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lastSalaryPaidMonth", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSalaryPaidYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("taxProofStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("taxProofRemark", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("foodReimbursementStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("foodReimbursementAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("travelRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("travelRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("travelRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("travelRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hotelRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hotelRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hotelRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hotelRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("internationalRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("internationalRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("internationalRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("internationalRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("educationRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("educationRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("educationRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("educationRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningBonusRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningBonusRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("joiningRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("joiningRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noticePeriodRecoveryAmt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noticePeriodRecoveryStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("noticePeriodRecoveryApproved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("noticePeriodRecoveryComment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("updatedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NOTICE_FinanceForm (id_ LONG not null primary key,exitId LONG,lastSalaryPaidDays LONG,lastSalaryPaidMonth VARCHAR(75) null,lastSalaryPaidYear VARCHAR(75) null,taxProofStatus INTEGER,taxProofRemark VARCHAR(200) null,foodReimbursementStatus INTEGER,foodReimbursementAmt VARCHAR(75) null,travelRecoveryAmt VARCHAR(75) null,travelRecoveryStatus INTEGER,travelRecoveryApproved BOOLEAN,travelRecoveryComment VARCHAR(500) null,hotelRecoveryAmt VARCHAR(75) null,hotelRecoveryStatus INTEGER,hotelRecoveryApproved BOOLEAN,hotelRecoveryComment VARCHAR(500) null,internationalRecoveryAmt VARCHAR(75) null,internationalRecoveryStatus INTEGER,internationalRecoveryApproved BOOLEAN,internationalRecoveryComment VARCHAR(500) null,educationRecoveryAmt VARCHAR(75) null,educationRecoveryStatus INTEGER,educationRecoveryApproved BOOLEAN,educationRecoveryComment VARCHAR(500) null,joiningBonusRecoveryAmt VARCHAR(75) null,joiningBonusRecoveryStatus INTEGER,joiningRecoveryApproved BOOLEAN,joiningRecoveryComment VARCHAR(500) null,noticePeriodRecoveryAmt VARCHAR(75) null,noticePeriodRecoveryStatus INTEGER,noticePeriodRecoveryApproved BOOLEAN,noticePeriodRecoveryComment VARCHAR(500) null,updatedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table NOTICE_FinanceForm";

	public static final String ORDER_BY_JPQL = " ORDER BY financeForm.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NOTICE_FinanceForm.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FinanceFormModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FinanceForm.class;
	}

	@Override
	public String getModelClassName() {
		return FinanceForm.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FinanceForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FinanceForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinanceForm, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FinanceForm)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FinanceForm, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FinanceForm, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FinanceForm)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FinanceForm, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FinanceForm, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FinanceForm, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FinanceForm, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FinanceForm, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FinanceForm, Object>>();
		Map<String, BiConsumer<FinanceForm, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FinanceForm, ?>>();

		attributeGetterFunctions.put("id", FinanceForm::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<FinanceForm, Long>)FinanceForm::setId);
		attributeGetterFunctions.put("exitId", FinanceForm::getExitId);
		attributeSetterBiConsumers.put(
			"exitId", (BiConsumer<FinanceForm, Long>)FinanceForm::setExitId);
		attributeGetterFunctions.put(
			"lastSalaryPaidDays", FinanceForm::getLastSalaryPaidDays);
		attributeSetterBiConsumers.put(
			"lastSalaryPaidDays",
			(BiConsumer<FinanceForm, Long>)FinanceForm::setLastSalaryPaidDays);
		attributeGetterFunctions.put(
			"lastSalaryPaidMonth", FinanceForm::getLastSalaryPaidMonth);
		attributeSetterBiConsumers.put(
			"lastSalaryPaidMonth",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setLastSalaryPaidMonth);
		attributeGetterFunctions.put(
			"lastSalaryPaidYear", FinanceForm::getLastSalaryPaidYear);
		attributeSetterBiConsumers.put(
			"lastSalaryPaidYear",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setLastSalaryPaidYear);
		attributeGetterFunctions.put(
			"taxProofStatus", FinanceForm::getTaxProofStatus);
		attributeSetterBiConsumers.put(
			"taxProofStatus",
			(BiConsumer<FinanceForm, Integer>)FinanceForm::setTaxProofStatus);
		attributeGetterFunctions.put(
			"taxProofRemark", FinanceForm::getTaxProofRemark);
		attributeSetterBiConsumers.put(
			"taxProofRemark",
			(BiConsumer<FinanceForm, String>)FinanceForm::setTaxProofRemark);
		attributeGetterFunctions.put(
			"foodReimbursementStatus", FinanceForm::getFoodReimbursementStatus);
		attributeSetterBiConsumers.put(
			"foodReimbursementStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setFoodReimbursementStatus);
		attributeGetterFunctions.put(
			"foodReimbursementAmt", FinanceForm::getFoodReimbursementAmt);
		attributeSetterBiConsumers.put(
			"foodReimbursementAmt",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setFoodReimbursementAmt);
		attributeGetterFunctions.put(
			"travelRecoveryAmt", FinanceForm::getTravelRecoveryAmt);
		attributeSetterBiConsumers.put(
			"travelRecoveryAmt",
			(BiConsumer<FinanceForm, String>)FinanceForm::setTravelRecoveryAmt);
		attributeGetterFunctions.put(
			"travelRecoveryStatus", FinanceForm::getTravelRecoveryStatus);
		attributeSetterBiConsumers.put(
			"travelRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setTravelRecoveryStatus);
		attributeGetterFunctions.put(
			"travelRecoveryApproved", FinanceForm::getTravelRecoveryApproved);
		attributeSetterBiConsumers.put(
			"travelRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setTravelRecoveryApproved);
		attributeGetterFunctions.put(
			"travelRecoveryComment", FinanceForm::getTravelRecoveryComment);
		attributeSetterBiConsumers.put(
			"travelRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setTravelRecoveryComment);
		attributeGetterFunctions.put(
			"hotelRecoveryAmt", FinanceForm::getHotelRecoveryAmt);
		attributeSetterBiConsumers.put(
			"hotelRecoveryAmt",
			(BiConsumer<FinanceForm, String>)FinanceForm::setHotelRecoveryAmt);
		attributeGetterFunctions.put(
			"hotelRecoveryStatus", FinanceForm::getHotelRecoveryStatus);
		attributeSetterBiConsumers.put(
			"hotelRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setHotelRecoveryStatus);
		attributeGetterFunctions.put(
			"hotelRecoveryApproved", FinanceForm::getHotelRecoveryApproved);
		attributeSetterBiConsumers.put(
			"hotelRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setHotelRecoveryApproved);
		attributeGetterFunctions.put(
			"hotelRecoveryComment", FinanceForm::getHotelRecoveryComment);
		attributeSetterBiConsumers.put(
			"hotelRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setHotelRecoveryComment);
		attributeGetterFunctions.put(
			"internationalRecoveryAmt",
			FinanceForm::getInternationalRecoveryAmt);
		attributeSetterBiConsumers.put(
			"internationalRecoveryAmt",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setInternationalRecoveryAmt);
		attributeGetterFunctions.put(
			"internationalRecoveryStatus",
			FinanceForm::getInternationalRecoveryStatus);
		attributeSetterBiConsumers.put(
			"internationalRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setInternationalRecoveryStatus);
		attributeGetterFunctions.put(
			"internationalRecoveryApproved",
			FinanceForm::getInternationalRecoveryApproved);
		attributeSetterBiConsumers.put(
			"internationalRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setInternationalRecoveryApproved);
		attributeGetterFunctions.put(
			"internationalRecoveryComment",
			FinanceForm::getInternationalRecoveryComment);
		attributeSetterBiConsumers.put(
			"internationalRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setInternationalRecoveryComment);
		attributeGetterFunctions.put(
			"educationRecoveryAmt", FinanceForm::getEducationRecoveryAmt);
		attributeSetterBiConsumers.put(
			"educationRecoveryAmt",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setEducationRecoveryAmt);
		attributeGetterFunctions.put(
			"educationRecoveryStatus", FinanceForm::getEducationRecoveryStatus);
		attributeSetterBiConsumers.put(
			"educationRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setEducationRecoveryStatus);
		attributeGetterFunctions.put(
			"educationRecoveryApproved",
			FinanceForm::getEducationRecoveryApproved);
		attributeSetterBiConsumers.put(
			"educationRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setEducationRecoveryApproved);
		attributeGetterFunctions.put(
			"educationRecoveryComment",
			FinanceForm::getEducationRecoveryComment);
		attributeSetterBiConsumers.put(
			"educationRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setEducationRecoveryComment);
		attributeGetterFunctions.put(
			"joiningBonusRecoveryAmt", FinanceForm::getJoiningBonusRecoveryAmt);
		attributeSetterBiConsumers.put(
			"joiningBonusRecoveryAmt",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setJoiningBonusRecoveryAmt);
		attributeGetterFunctions.put(
			"joiningBonusRecoveryStatus",
			FinanceForm::getJoiningBonusRecoveryStatus);
		attributeSetterBiConsumers.put(
			"joiningBonusRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setJoiningBonusRecoveryStatus);
		attributeGetterFunctions.put(
			"joiningRecoveryApproved", FinanceForm::getJoiningRecoveryApproved);
		attributeSetterBiConsumers.put(
			"joiningRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setJoiningRecoveryApproved);
		attributeGetterFunctions.put(
			"joiningRecoveryComment", FinanceForm::getJoiningRecoveryComment);
		attributeSetterBiConsumers.put(
			"joiningRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setJoiningRecoveryComment);
		attributeGetterFunctions.put(
			"noticePeriodRecoveryAmt", FinanceForm::getNoticePeriodRecoveryAmt);
		attributeSetterBiConsumers.put(
			"noticePeriodRecoveryAmt",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setNoticePeriodRecoveryAmt);
		attributeGetterFunctions.put(
			"noticePeriodRecoveryStatus",
			FinanceForm::getNoticePeriodRecoveryStatus);
		attributeSetterBiConsumers.put(
			"noticePeriodRecoveryStatus",
			(BiConsumer<FinanceForm, Integer>)
				FinanceForm::setNoticePeriodRecoveryStatus);
		attributeGetterFunctions.put(
			"noticePeriodRecoveryApproved",
			FinanceForm::getNoticePeriodRecoveryApproved);
		attributeSetterBiConsumers.put(
			"noticePeriodRecoveryApproved",
			(BiConsumer<FinanceForm, Boolean>)
				FinanceForm::setNoticePeriodRecoveryApproved);
		attributeGetterFunctions.put(
			"noticePeriodRecoveryComment",
			FinanceForm::getNoticePeriodRecoveryComment);
		attributeSetterBiConsumers.put(
			"noticePeriodRecoveryComment",
			(BiConsumer<FinanceForm, String>)
				FinanceForm::setNoticePeriodRecoveryComment);
		attributeGetterFunctions.put(
			"updatedDate", FinanceForm::getUpdatedDate);
		attributeSetterBiConsumers.put(
			"updatedDate",
			(BiConsumer<FinanceForm, Date>)FinanceForm::setUpdatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getExitId() {
		return _exitId;
	}

	@Override
	public void setExitId(long exitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exitId = exitId;
	}

	@Override
	public long getLastSalaryPaidDays() {
		return _lastSalaryPaidDays;
	}

	@Override
	public void setLastSalaryPaidDays(long lastSalaryPaidDays) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastSalaryPaidDays = lastSalaryPaidDays;
	}

	@Override
	public String getLastSalaryPaidMonth() {
		if (_lastSalaryPaidMonth == null) {
			return "";
		}
		else {
			return _lastSalaryPaidMonth;
		}
	}

	@Override
	public void setLastSalaryPaidMonth(String lastSalaryPaidMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastSalaryPaidMonth = lastSalaryPaidMonth;
	}

	@Override
	public String getLastSalaryPaidYear() {
		if (_lastSalaryPaidYear == null) {
			return "";
		}
		else {
			return _lastSalaryPaidYear;
		}
	}

	@Override
	public void setLastSalaryPaidYear(String lastSalaryPaidYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastSalaryPaidYear = lastSalaryPaidYear;
	}

	@Override
	public int getTaxProofStatus() {
		return _taxProofStatus;
	}

	@Override
	public void setTaxProofStatus(int taxProofStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taxProofStatus = taxProofStatus;
	}

	@Override
	public String getTaxProofRemark() {
		if (_taxProofRemark == null) {
			return "";
		}
		else {
			return _taxProofRemark;
		}
	}

	@Override
	public void setTaxProofRemark(String taxProofRemark) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taxProofRemark = taxProofRemark;
	}

	@Override
	public int getFoodReimbursementStatus() {
		return _foodReimbursementStatus;
	}

	@Override
	public void setFoodReimbursementStatus(int foodReimbursementStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_foodReimbursementStatus = foodReimbursementStatus;
	}

	@Override
	public String getFoodReimbursementAmt() {
		if (_foodReimbursementAmt == null) {
			return "";
		}
		else {
			return _foodReimbursementAmt;
		}
	}

	@Override
	public void setFoodReimbursementAmt(String foodReimbursementAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_foodReimbursementAmt = foodReimbursementAmt;
	}

	@Override
	public String getTravelRecoveryAmt() {
		if (_travelRecoveryAmt == null) {
			return "";
		}
		else {
			return _travelRecoveryAmt;
		}
	}

	@Override
	public void setTravelRecoveryAmt(String travelRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelRecoveryAmt = travelRecoveryAmt;
	}

	@Override
	public int getTravelRecoveryStatus() {
		return _travelRecoveryStatus;
	}

	@Override
	public void setTravelRecoveryStatus(int travelRecoveryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelRecoveryStatus = travelRecoveryStatus;
	}

	@Override
	public boolean getTravelRecoveryApproved() {
		return _travelRecoveryApproved;
	}

	@Override
	public boolean isTravelRecoveryApproved() {
		return _travelRecoveryApproved;
	}

	@Override
	public void setTravelRecoveryApproved(boolean travelRecoveryApproved) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelRecoveryApproved = travelRecoveryApproved;
	}

	@Override
	public String getTravelRecoveryComment() {
		if (_travelRecoveryComment == null) {
			return "";
		}
		else {
			return _travelRecoveryComment;
		}
	}

	@Override
	public void setTravelRecoveryComment(String travelRecoveryComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelRecoveryComment = travelRecoveryComment;
	}

	@Override
	public String getHotelRecoveryAmt() {
		if (_hotelRecoveryAmt == null) {
			return "";
		}
		else {
			return _hotelRecoveryAmt;
		}
	}

	@Override
	public void setHotelRecoveryAmt(String hotelRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hotelRecoveryAmt = hotelRecoveryAmt;
	}

	@Override
	public int getHotelRecoveryStatus() {
		return _hotelRecoveryStatus;
	}

	@Override
	public void setHotelRecoveryStatus(int hotelRecoveryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hotelRecoveryStatus = hotelRecoveryStatus;
	}

	@Override
	public boolean getHotelRecoveryApproved() {
		return _hotelRecoveryApproved;
	}

	@Override
	public boolean isHotelRecoveryApproved() {
		return _hotelRecoveryApproved;
	}

	@Override
	public void setHotelRecoveryApproved(boolean hotelRecoveryApproved) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hotelRecoveryApproved = hotelRecoveryApproved;
	}

	@Override
	public String getHotelRecoveryComment() {
		if (_hotelRecoveryComment == null) {
			return "";
		}
		else {
			return _hotelRecoveryComment;
		}
	}

	@Override
	public void setHotelRecoveryComment(String hotelRecoveryComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hotelRecoveryComment = hotelRecoveryComment;
	}

	@Override
	public String getInternationalRecoveryAmt() {
		if (_internationalRecoveryAmt == null) {
			return "";
		}
		else {
			return _internationalRecoveryAmt;
		}
	}

	@Override
	public void setInternationalRecoveryAmt(String internationalRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_internationalRecoveryAmt = internationalRecoveryAmt;
	}

	@Override
	public int getInternationalRecoveryStatus() {
		return _internationalRecoveryStatus;
	}

	@Override
	public void setInternationalRecoveryStatus(
		int internationalRecoveryStatus) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_internationalRecoveryStatus = internationalRecoveryStatus;
	}

	@Override
	public boolean getInternationalRecoveryApproved() {
		return _internationalRecoveryApproved;
	}

	@Override
	public boolean isInternationalRecoveryApproved() {
		return _internationalRecoveryApproved;
	}

	@Override
	public void setInternationalRecoveryApproved(
		boolean internationalRecoveryApproved) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_internationalRecoveryApproved = internationalRecoveryApproved;
	}

	@Override
	public String getInternationalRecoveryComment() {
		if (_internationalRecoveryComment == null) {
			return "";
		}
		else {
			return _internationalRecoveryComment;
		}
	}

	@Override
	public void setInternationalRecoveryComment(
		String internationalRecoveryComment) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_internationalRecoveryComment = internationalRecoveryComment;
	}

	@Override
	public String getEducationRecoveryAmt() {
		if (_educationRecoveryAmt == null) {
			return "";
		}
		else {
			return _educationRecoveryAmt;
		}
	}

	@Override
	public void setEducationRecoveryAmt(String educationRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationRecoveryAmt = educationRecoveryAmt;
	}

	@Override
	public int getEducationRecoveryStatus() {
		return _educationRecoveryStatus;
	}

	@Override
	public void setEducationRecoveryStatus(int educationRecoveryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationRecoveryStatus = educationRecoveryStatus;
	}

	@Override
	public boolean getEducationRecoveryApproved() {
		return _educationRecoveryApproved;
	}

	@Override
	public boolean isEducationRecoveryApproved() {
		return _educationRecoveryApproved;
	}

	@Override
	public void setEducationRecoveryApproved(
		boolean educationRecoveryApproved) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationRecoveryApproved = educationRecoveryApproved;
	}

	@Override
	public String getEducationRecoveryComment() {
		if (_educationRecoveryComment == null) {
			return "";
		}
		else {
			return _educationRecoveryComment;
		}
	}

	@Override
	public void setEducationRecoveryComment(String educationRecoveryComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationRecoveryComment = educationRecoveryComment;
	}

	@Override
	public String getJoiningBonusRecoveryAmt() {
		if (_joiningBonusRecoveryAmt == null) {
			return "";
		}
		else {
			return _joiningBonusRecoveryAmt;
		}
	}

	@Override
	public void setJoiningBonusRecoveryAmt(String joiningBonusRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningBonusRecoveryAmt = joiningBonusRecoveryAmt;
	}

	@Override
	public int getJoiningBonusRecoveryStatus() {
		return _joiningBonusRecoveryStatus;
	}

	@Override
	public void setJoiningBonusRecoveryStatus(int joiningBonusRecoveryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningBonusRecoveryStatus = joiningBonusRecoveryStatus;
	}

	@Override
	public boolean getJoiningRecoveryApproved() {
		return _joiningRecoveryApproved;
	}

	@Override
	public boolean isJoiningRecoveryApproved() {
		return _joiningRecoveryApproved;
	}

	@Override
	public void setJoiningRecoveryApproved(boolean joiningRecoveryApproved) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningRecoveryApproved = joiningRecoveryApproved;
	}

	@Override
	public String getJoiningRecoveryComment() {
		if (_joiningRecoveryComment == null) {
			return "";
		}
		else {
			return _joiningRecoveryComment;
		}
	}

	@Override
	public void setJoiningRecoveryComment(String joiningRecoveryComment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningRecoveryComment = joiningRecoveryComment;
	}

	@Override
	public String getNoticePeriodRecoveryAmt() {
		if (_noticePeriodRecoveryAmt == null) {
			return "";
		}
		else {
			return _noticePeriodRecoveryAmt;
		}
	}

	@Override
	public void setNoticePeriodRecoveryAmt(String noticePeriodRecoveryAmt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noticePeriodRecoveryAmt = noticePeriodRecoveryAmt;
	}

	@Override
	public int getNoticePeriodRecoveryStatus() {
		return _noticePeriodRecoveryStatus;
	}

	@Override
	public void setNoticePeriodRecoveryStatus(int noticePeriodRecoveryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noticePeriodRecoveryStatus = noticePeriodRecoveryStatus;
	}

	@Override
	public boolean getNoticePeriodRecoveryApproved() {
		return _noticePeriodRecoveryApproved;
	}

	@Override
	public boolean isNoticePeriodRecoveryApproved() {
		return _noticePeriodRecoveryApproved;
	}

	@Override
	public void setNoticePeriodRecoveryApproved(
		boolean noticePeriodRecoveryApproved) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noticePeriodRecoveryApproved = noticePeriodRecoveryApproved;
	}

	@Override
	public String getNoticePeriodRecoveryComment() {
		if (_noticePeriodRecoveryComment == null) {
			return "";
		}
		else {
			return _noticePeriodRecoveryComment;
		}
	}

	@Override
	public void setNoticePeriodRecoveryComment(
		String noticePeriodRecoveryComment) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noticePeriodRecoveryComment = noticePeriodRecoveryComment;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FinanceForm.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FinanceForm toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FinanceForm>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FinanceFormImpl financeFormImpl = new FinanceFormImpl();

		financeFormImpl.setId(getId());
		financeFormImpl.setExitId(getExitId());
		financeFormImpl.setLastSalaryPaidDays(getLastSalaryPaidDays());
		financeFormImpl.setLastSalaryPaidMonth(getLastSalaryPaidMonth());
		financeFormImpl.setLastSalaryPaidYear(getLastSalaryPaidYear());
		financeFormImpl.setTaxProofStatus(getTaxProofStatus());
		financeFormImpl.setTaxProofRemark(getTaxProofRemark());
		financeFormImpl.setFoodReimbursementStatus(
			getFoodReimbursementStatus());
		financeFormImpl.setFoodReimbursementAmt(getFoodReimbursementAmt());
		financeFormImpl.setTravelRecoveryAmt(getTravelRecoveryAmt());
		financeFormImpl.setTravelRecoveryStatus(getTravelRecoveryStatus());
		financeFormImpl.setTravelRecoveryApproved(isTravelRecoveryApproved());
		financeFormImpl.setTravelRecoveryComment(getTravelRecoveryComment());
		financeFormImpl.setHotelRecoveryAmt(getHotelRecoveryAmt());
		financeFormImpl.setHotelRecoveryStatus(getHotelRecoveryStatus());
		financeFormImpl.setHotelRecoveryApproved(isHotelRecoveryApproved());
		financeFormImpl.setHotelRecoveryComment(getHotelRecoveryComment());
		financeFormImpl.setInternationalRecoveryAmt(
			getInternationalRecoveryAmt());
		financeFormImpl.setInternationalRecoveryStatus(
			getInternationalRecoveryStatus());
		financeFormImpl.setInternationalRecoveryApproved(
			isInternationalRecoveryApproved());
		financeFormImpl.setInternationalRecoveryComment(
			getInternationalRecoveryComment());
		financeFormImpl.setEducationRecoveryAmt(getEducationRecoveryAmt());
		financeFormImpl.setEducationRecoveryStatus(
			getEducationRecoveryStatus());
		financeFormImpl.setEducationRecoveryApproved(
			isEducationRecoveryApproved());
		financeFormImpl.setEducationRecoveryComment(
			getEducationRecoveryComment());
		financeFormImpl.setJoiningBonusRecoveryAmt(
			getJoiningBonusRecoveryAmt());
		financeFormImpl.setJoiningBonusRecoveryStatus(
			getJoiningBonusRecoveryStatus());
		financeFormImpl.setJoiningRecoveryApproved(isJoiningRecoveryApproved());
		financeFormImpl.setJoiningRecoveryComment(getJoiningRecoveryComment());
		financeFormImpl.setNoticePeriodRecoveryAmt(
			getNoticePeriodRecoveryAmt());
		financeFormImpl.setNoticePeriodRecoveryStatus(
			getNoticePeriodRecoveryStatus());
		financeFormImpl.setNoticePeriodRecoveryApproved(
			isNoticePeriodRecoveryApproved());
		financeFormImpl.setNoticePeriodRecoveryComment(
			getNoticePeriodRecoveryComment());
		financeFormImpl.setUpdatedDate(getUpdatedDate());

		financeFormImpl.resetOriginalValues();

		return financeFormImpl;
	}

	@Override
	public FinanceForm cloneWithOriginalValues() {
		FinanceFormImpl financeFormImpl = new FinanceFormImpl();

		financeFormImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		financeFormImpl.setExitId(this.<Long>getColumnOriginalValue("exitId"));
		financeFormImpl.setLastSalaryPaidDays(
			this.<Long>getColumnOriginalValue("lastSalaryPaidDays"));
		financeFormImpl.setLastSalaryPaidMonth(
			this.<String>getColumnOriginalValue("lastSalaryPaidMonth"));
		financeFormImpl.setLastSalaryPaidYear(
			this.<String>getColumnOriginalValue("lastSalaryPaidYear"));
		financeFormImpl.setTaxProofStatus(
			this.<Integer>getColumnOriginalValue("taxProofStatus"));
		financeFormImpl.setTaxProofRemark(
			this.<String>getColumnOriginalValue("taxProofRemark"));
		financeFormImpl.setFoodReimbursementStatus(
			this.<Integer>getColumnOriginalValue("foodReimbursementStatus"));
		financeFormImpl.setFoodReimbursementAmt(
			this.<String>getColumnOriginalValue("foodReimbursementAmt"));
		financeFormImpl.setTravelRecoveryAmt(
			this.<String>getColumnOriginalValue("travelRecoveryAmt"));
		financeFormImpl.setTravelRecoveryStatus(
			this.<Integer>getColumnOriginalValue("travelRecoveryStatus"));
		financeFormImpl.setTravelRecoveryApproved(
			this.<Boolean>getColumnOriginalValue("travelRecoveryApproved"));
		financeFormImpl.setTravelRecoveryComment(
			this.<String>getColumnOriginalValue("travelRecoveryComment"));
		financeFormImpl.setHotelRecoveryAmt(
			this.<String>getColumnOriginalValue("hotelRecoveryAmt"));
		financeFormImpl.setHotelRecoveryStatus(
			this.<Integer>getColumnOriginalValue("hotelRecoveryStatus"));
		financeFormImpl.setHotelRecoveryApproved(
			this.<Boolean>getColumnOriginalValue("hotelRecoveryApproved"));
		financeFormImpl.setHotelRecoveryComment(
			this.<String>getColumnOriginalValue("hotelRecoveryComment"));
		financeFormImpl.setInternationalRecoveryAmt(
			this.<String>getColumnOriginalValue("internationalRecoveryAmt"));
		financeFormImpl.setInternationalRecoveryStatus(
			this.<Integer>getColumnOriginalValue(
				"internationalRecoveryStatus"));
		financeFormImpl.setInternationalRecoveryApproved(
			this.<Boolean>getColumnOriginalValue(
				"internationalRecoveryApproved"));
		financeFormImpl.setInternationalRecoveryComment(
			this.<String>getColumnOriginalValue(
				"internationalRecoveryComment"));
		financeFormImpl.setEducationRecoveryAmt(
			this.<String>getColumnOriginalValue("educationRecoveryAmt"));
		financeFormImpl.setEducationRecoveryStatus(
			this.<Integer>getColumnOriginalValue("educationRecoveryStatus"));
		financeFormImpl.setEducationRecoveryApproved(
			this.<Boolean>getColumnOriginalValue("educationRecoveryApproved"));
		financeFormImpl.setEducationRecoveryComment(
			this.<String>getColumnOriginalValue("educationRecoveryComment"));
		financeFormImpl.setJoiningBonusRecoveryAmt(
			this.<String>getColumnOriginalValue("joiningBonusRecoveryAmt"));
		financeFormImpl.setJoiningBonusRecoveryStatus(
			this.<Integer>getColumnOriginalValue("joiningBonusRecoveryStatus"));
		financeFormImpl.setJoiningRecoveryApproved(
			this.<Boolean>getColumnOriginalValue("joiningRecoveryApproved"));
		financeFormImpl.setJoiningRecoveryComment(
			this.<String>getColumnOriginalValue("joiningRecoveryComment"));
		financeFormImpl.setNoticePeriodRecoveryAmt(
			this.<String>getColumnOriginalValue("noticePeriodRecoveryAmt"));
		financeFormImpl.setNoticePeriodRecoveryStatus(
			this.<Integer>getColumnOriginalValue("noticePeriodRecoveryStatus"));
		financeFormImpl.setNoticePeriodRecoveryApproved(
			this.<Boolean>getColumnOriginalValue(
				"noticePeriodRecoveryApproved"));
		financeFormImpl.setNoticePeriodRecoveryComment(
			this.<String>getColumnOriginalValue("noticePeriodRecoveryComment"));
		financeFormImpl.setUpdatedDate(
			this.<Date>getColumnOriginalValue("updatedDate"));

		return financeFormImpl;
	}

	@Override
	public int compareTo(FinanceForm financeForm) {
		long primaryKey = financeForm.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FinanceForm)) {
			return false;
		}

		FinanceForm financeForm = (FinanceForm)object;

		long primaryKey = financeForm.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FinanceForm> toCacheModel() {
		FinanceFormCacheModel financeFormCacheModel =
			new FinanceFormCacheModel();

		financeFormCacheModel.id = getId();

		financeFormCacheModel.exitId = getExitId();

		financeFormCacheModel.lastSalaryPaidDays = getLastSalaryPaidDays();

		financeFormCacheModel.lastSalaryPaidMonth = getLastSalaryPaidMonth();

		String lastSalaryPaidMonth = financeFormCacheModel.lastSalaryPaidMonth;

		if ((lastSalaryPaidMonth != null) &&
			(lastSalaryPaidMonth.length() == 0)) {

			financeFormCacheModel.lastSalaryPaidMonth = null;
		}

		financeFormCacheModel.lastSalaryPaidYear = getLastSalaryPaidYear();

		String lastSalaryPaidYear = financeFormCacheModel.lastSalaryPaidYear;

		if ((lastSalaryPaidYear != null) &&
			(lastSalaryPaidYear.length() == 0)) {

			financeFormCacheModel.lastSalaryPaidYear = null;
		}

		financeFormCacheModel.taxProofStatus = getTaxProofStatus();

		financeFormCacheModel.taxProofRemark = getTaxProofRemark();

		String taxProofRemark = financeFormCacheModel.taxProofRemark;

		if ((taxProofRemark != null) && (taxProofRemark.length() == 0)) {
			financeFormCacheModel.taxProofRemark = null;
		}

		financeFormCacheModel.foodReimbursementStatus =
			getFoodReimbursementStatus();

		financeFormCacheModel.foodReimbursementAmt = getFoodReimbursementAmt();

		String foodReimbursementAmt =
			financeFormCacheModel.foodReimbursementAmt;

		if ((foodReimbursementAmt != null) &&
			(foodReimbursementAmt.length() == 0)) {

			financeFormCacheModel.foodReimbursementAmt = null;
		}

		financeFormCacheModel.travelRecoveryAmt = getTravelRecoveryAmt();

		String travelRecoveryAmt = financeFormCacheModel.travelRecoveryAmt;

		if ((travelRecoveryAmt != null) && (travelRecoveryAmt.length() == 0)) {
			financeFormCacheModel.travelRecoveryAmt = null;
		}

		financeFormCacheModel.travelRecoveryStatus = getTravelRecoveryStatus();

		financeFormCacheModel.travelRecoveryApproved =
			isTravelRecoveryApproved();

		financeFormCacheModel.travelRecoveryComment =
			getTravelRecoveryComment();

		String travelRecoveryComment =
			financeFormCacheModel.travelRecoveryComment;

		if ((travelRecoveryComment != null) &&
			(travelRecoveryComment.length() == 0)) {

			financeFormCacheModel.travelRecoveryComment = null;
		}

		financeFormCacheModel.hotelRecoveryAmt = getHotelRecoveryAmt();

		String hotelRecoveryAmt = financeFormCacheModel.hotelRecoveryAmt;

		if ((hotelRecoveryAmt != null) && (hotelRecoveryAmt.length() == 0)) {
			financeFormCacheModel.hotelRecoveryAmt = null;
		}

		financeFormCacheModel.hotelRecoveryStatus = getHotelRecoveryStatus();

		financeFormCacheModel.hotelRecoveryApproved = isHotelRecoveryApproved();

		financeFormCacheModel.hotelRecoveryComment = getHotelRecoveryComment();

		String hotelRecoveryComment =
			financeFormCacheModel.hotelRecoveryComment;

		if ((hotelRecoveryComment != null) &&
			(hotelRecoveryComment.length() == 0)) {

			financeFormCacheModel.hotelRecoveryComment = null;
		}

		financeFormCacheModel.internationalRecoveryAmt =
			getInternationalRecoveryAmt();

		String internationalRecoveryAmt =
			financeFormCacheModel.internationalRecoveryAmt;

		if ((internationalRecoveryAmt != null) &&
			(internationalRecoveryAmt.length() == 0)) {

			financeFormCacheModel.internationalRecoveryAmt = null;
		}

		financeFormCacheModel.internationalRecoveryStatus =
			getInternationalRecoveryStatus();

		financeFormCacheModel.internationalRecoveryApproved =
			isInternationalRecoveryApproved();

		financeFormCacheModel.internationalRecoveryComment =
			getInternationalRecoveryComment();

		String internationalRecoveryComment =
			financeFormCacheModel.internationalRecoveryComment;

		if ((internationalRecoveryComment != null) &&
			(internationalRecoveryComment.length() == 0)) {

			financeFormCacheModel.internationalRecoveryComment = null;
		}

		financeFormCacheModel.educationRecoveryAmt = getEducationRecoveryAmt();

		String educationRecoveryAmt =
			financeFormCacheModel.educationRecoveryAmt;

		if ((educationRecoveryAmt != null) &&
			(educationRecoveryAmt.length() == 0)) {

			financeFormCacheModel.educationRecoveryAmt = null;
		}

		financeFormCacheModel.educationRecoveryStatus =
			getEducationRecoveryStatus();

		financeFormCacheModel.educationRecoveryApproved =
			isEducationRecoveryApproved();

		financeFormCacheModel.educationRecoveryComment =
			getEducationRecoveryComment();

		String educationRecoveryComment =
			financeFormCacheModel.educationRecoveryComment;

		if ((educationRecoveryComment != null) &&
			(educationRecoveryComment.length() == 0)) {

			financeFormCacheModel.educationRecoveryComment = null;
		}

		financeFormCacheModel.joiningBonusRecoveryAmt =
			getJoiningBonusRecoveryAmt();

		String joiningBonusRecoveryAmt =
			financeFormCacheModel.joiningBonusRecoveryAmt;

		if ((joiningBonusRecoveryAmt != null) &&
			(joiningBonusRecoveryAmt.length() == 0)) {

			financeFormCacheModel.joiningBonusRecoveryAmt = null;
		}

		financeFormCacheModel.joiningBonusRecoveryStatus =
			getJoiningBonusRecoveryStatus();

		financeFormCacheModel.joiningRecoveryApproved =
			isJoiningRecoveryApproved();

		financeFormCacheModel.joiningRecoveryComment =
			getJoiningRecoveryComment();

		String joiningRecoveryComment =
			financeFormCacheModel.joiningRecoveryComment;

		if ((joiningRecoveryComment != null) &&
			(joiningRecoveryComment.length() == 0)) {

			financeFormCacheModel.joiningRecoveryComment = null;
		}

		financeFormCacheModel.noticePeriodRecoveryAmt =
			getNoticePeriodRecoveryAmt();

		String noticePeriodRecoveryAmt =
			financeFormCacheModel.noticePeriodRecoveryAmt;

		if ((noticePeriodRecoveryAmt != null) &&
			(noticePeriodRecoveryAmt.length() == 0)) {

			financeFormCacheModel.noticePeriodRecoveryAmt = null;
		}

		financeFormCacheModel.noticePeriodRecoveryStatus =
			getNoticePeriodRecoveryStatus();

		financeFormCacheModel.noticePeriodRecoveryApproved =
			isNoticePeriodRecoveryApproved();

		financeFormCacheModel.noticePeriodRecoveryComment =
			getNoticePeriodRecoveryComment();

		String noticePeriodRecoveryComment =
			financeFormCacheModel.noticePeriodRecoveryComment;

		if ((noticePeriodRecoveryComment != null) &&
			(noticePeriodRecoveryComment.length() == 0)) {

			financeFormCacheModel.noticePeriodRecoveryComment = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			financeFormCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			financeFormCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return financeFormCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FinanceForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FinanceForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FinanceForm, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FinanceForm)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FinanceForm>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FinanceForm.class, ModelWrapper.class);

	}

	private long _id;
	private long _exitId;
	private long _lastSalaryPaidDays;
	private String _lastSalaryPaidMonth;
	private String _lastSalaryPaidYear;
	private int _taxProofStatus;
	private String _taxProofRemark;
	private int _foodReimbursementStatus;
	private String _foodReimbursementAmt;
	private String _travelRecoveryAmt;
	private int _travelRecoveryStatus;
	private boolean _travelRecoveryApproved;
	private String _travelRecoveryComment;
	private String _hotelRecoveryAmt;
	private int _hotelRecoveryStatus;
	private boolean _hotelRecoveryApproved;
	private String _hotelRecoveryComment;
	private String _internationalRecoveryAmt;
	private int _internationalRecoveryStatus;
	private boolean _internationalRecoveryApproved;
	private String _internationalRecoveryComment;
	private String _educationRecoveryAmt;
	private int _educationRecoveryStatus;
	private boolean _educationRecoveryApproved;
	private String _educationRecoveryComment;
	private String _joiningBonusRecoveryAmt;
	private int _joiningBonusRecoveryStatus;
	private boolean _joiningRecoveryApproved;
	private String _joiningRecoveryComment;
	private String _noticePeriodRecoveryAmt;
	private int _noticePeriodRecoveryStatus;
	private boolean _noticePeriodRecoveryApproved;
	private String _noticePeriodRecoveryComment;
	private Date _updatedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FinanceForm, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FinanceForm)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("exitId", _exitId);
		_columnOriginalValues.put("lastSalaryPaidDays", _lastSalaryPaidDays);
		_columnOriginalValues.put("lastSalaryPaidMonth", _lastSalaryPaidMonth);
		_columnOriginalValues.put("lastSalaryPaidYear", _lastSalaryPaidYear);
		_columnOriginalValues.put("taxProofStatus", _taxProofStatus);
		_columnOriginalValues.put("taxProofRemark", _taxProofRemark);
		_columnOriginalValues.put(
			"foodReimbursementStatus", _foodReimbursementStatus);
		_columnOriginalValues.put(
			"foodReimbursementAmt", _foodReimbursementAmt);
		_columnOriginalValues.put("travelRecoveryAmt", _travelRecoveryAmt);
		_columnOriginalValues.put(
			"travelRecoveryStatus", _travelRecoveryStatus);
		_columnOriginalValues.put(
			"travelRecoveryApproved", _travelRecoveryApproved);
		_columnOriginalValues.put(
			"travelRecoveryComment", _travelRecoveryComment);
		_columnOriginalValues.put("hotelRecoveryAmt", _hotelRecoveryAmt);
		_columnOriginalValues.put("hotelRecoveryStatus", _hotelRecoveryStatus);
		_columnOriginalValues.put(
			"hotelRecoveryApproved", _hotelRecoveryApproved);
		_columnOriginalValues.put(
			"hotelRecoveryComment", _hotelRecoveryComment);
		_columnOriginalValues.put(
			"internationalRecoveryAmt", _internationalRecoveryAmt);
		_columnOriginalValues.put(
			"internationalRecoveryStatus", _internationalRecoveryStatus);
		_columnOriginalValues.put(
			"internationalRecoveryApproved", _internationalRecoveryApproved);
		_columnOriginalValues.put(
			"internationalRecoveryComment", _internationalRecoveryComment);
		_columnOriginalValues.put(
			"educationRecoveryAmt", _educationRecoveryAmt);
		_columnOriginalValues.put(
			"educationRecoveryStatus", _educationRecoveryStatus);
		_columnOriginalValues.put(
			"educationRecoveryApproved", _educationRecoveryApproved);
		_columnOriginalValues.put(
			"educationRecoveryComment", _educationRecoveryComment);
		_columnOriginalValues.put(
			"joiningBonusRecoveryAmt", _joiningBonusRecoveryAmt);
		_columnOriginalValues.put(
			"joiningBonusRecoveryStatus", _joiningBonusRecoveryStatus);
		_columnOriginalValues.put(
			"joiningRecoveryApproved", _joiningRecoveryApproved);
		_columnOriginalValues.put(
			"joiningRecoveryComment", _joiningRecoveryComment);
		_columnOriginalValues.put(
			"noticePeriodRecoveryAmt", _noticePeriodRecoveryAmt);
		_columnOriginalValues.put(
			"noticePeriodRecoveryStatus", _noticePeriodRecoveryStatus);
		_columnOriginalValues.put(
			"noticePeriodRecoveryApproved", _noticePeriodRecoveryApproved);
		_columnOriginalValues.put(
			"noticePeriodRecoveryComment", _noticePeriodRecoveryComment);
		_columnOriginalValues.put("updatedDate", _updatedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("exitId", 2L);

		columnBitmasks.put("lastSalaryPaidDays", 4L);

		columnBitmasks.put("lastSalaryPaidMonth", 8L);

		columnBitmasks.put("lastSalaryPaidYear", 16L);

		columnBitmasks.put("taxProofStatus", 32L);

		columnBitmasks.put("taxProofRemark", 64L);

		columnBitmasks.put("foodReimbursementStatus", 128L);

		columnBitmasks.put("foodReimbursementAmt", 256L);

		columnBitmasks.put("travelRecoveryAmt", 512L);

		columnBitmasks.put("travelRecoveryStatus", 1024L);

		columnBitmasks.put("travelRecoveryApproved", 2048L);

		columnBitmasks.put("travelRecoveryComment", 4096L);

		columnBitmasks.put("hotelRecoveryAmt", 8192L);

		columnBitmasks.put("hotelRecoveryStatus", 16384L);

		columnBitmasks.put("hotelRecoveryApproved", 32768L);

		columnBitmasks.put("hotelRecoveryComment", 65536L);

		columnBitmasks.put("internationalRecoveryAmt", 131072L);

		columnBitmasks.put("internationalRecoveryStatus", 262144L);

		columnBitmasks.put("internationalRecoveryApproved", 524288L);

		columnBitmasks.put("internationalRecoveryComment", 1048576L);

		columnBitmasks.put("educationRecoveryAmt", 2097152L);

		columnBitmasks.put("educationRecoveryStatus", 4194304L);

		columnBitmasks.put("educationRecoveryApproved", 8388608L);

		columnBitmasks.put("educationRecoveryComment", 16777216L);

		columnBitmasks.put("joiningBonusRecoveryAmt", 33554432L);

		columnBitmasks.put("joiningBonusRecoveryStatus", 67108864L);

		columnBitmasks.put("joiningRecoveryApproved", 134217728L);

		columnBitmasks.put("joiningRecoveryComment", 268435456L);

		columnBitmasks.put("noticePeriodRecoveryAmt", 536870912L);

		columnBitmasks.put("noticePeriodRecoveryStatus", 1073741824L);

		columnBitmasks.put("noticePeriodRecoveryApproved", 2147483648L);

		columnBitmasks.put("noticePeriodRecoveryComment", 4294967296L);

		columnBitmasks.put("updatedDate", 8589934592L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FinanceForm _escapedModel;

}