create table NOTICE_AdminForm (
	id_ LONG not null primary key,
	exitId LONG,
	stationaryRecoveryAmt VARCHAR(75) null,
	stationaryRecoveryAmtStatus INTEGER,
	stationaryRecoveryApproved BOOLEAN,
	stationaryRecoveryComment VARCHAR(500) null,
	keysRecoveryAmt VARCHAR(75) null,
	keysRecoveryAmtStatus INTEGER,
	keyRecoveryApproved BOOLEAN,
	keyRecoveryComment VARCHAR(500) null,
	libraryRecoveryAmt VARCHAR(75) null,
	libraryRecoveryAmtStatus INTEGER,
	libraryRecoveryApproved BOOLEAN,
	libraryRecoveryComment VARCHAR(500) null,
	sportsRecoveryAmt VARCHAR(75) null,
	sportsRecoveryAmtStatus INTEGER,
	sportsRecoveryApproved BOOLEAN,
	sportsRecoveryComment VARCHAR(500) null,
	infraRecoveryAmt VARCHAR(75) null,
	infraRecoveryAmtStatus INTEGER,
	infraRecoveryApproved BOOLEAN,
	infraRecoveryComment VARCHAR(500) null,
	lunchRecoveryAmt VARCHAR(75) null,
	lunchRecoveryAmtStatus INTEGER,
	lunchRecoveryApproved BOOLEAN,
	lunchRecoveryComment VARCHAR(500) null,
	accessCardRecoveryAmt VARCHAR(75) null,
	accessCardRecoveryAmtStatus INTEGER,
	accessCardRecoveryApproved BOOLEAN,
	accessCardRecoveryComment VARCHAR(500) null,
	identityCardRecoveryAmt VARCHAR(75) null,
	identityCardRecoveryStatus INTEGER,
	identityCardRecoveryApproved BOOLEAN,
	identityCardRecoveryComment VARCHAR(500) null,
	updatedDate DATE null
);

create table NOTICE_ExitForm (
	id_ LONG not null primary key,
	resignationId LONG,
	managerFormStatus BOOLEAN,
	hrFormStatus BOOLEAN,
	itFormStatus BOOLEAN,
	adminFormStatus BOOLEAN,
	financeFormStatus BOOLEAN
);

create table NOTICE_ExitState (
	exitStateId LONG not null primary key,
	exitStateKey INTEGER,
	exitStateDescription VARCHAR(75) null,
	exitStateDisplay VARCHAR(75) null
);

create table NOTICE_FinanceForm (
	id_ LONG not null primary key,
	exitId LONG,
	lastSalaryPaidDays LONG,
	lastSalaryPaidMonth VARCHAR(75) null,
	lastSalaryPaidYear VARCHAR(75) null,
	taxProofStatus INTEGER,
	taxProofRemark VARCHAR(200) null,
	foodReimbursementStatus INTEGER,
	foodReimbursementAmt VARCHAR(75) null,
	travelRecoveryAmt VARCHAR(75) null,
	travelRecoveryStatus INTEGER,
	travelRecoveryApproved BOOLEAN,
	travelRecoveryComment VARCHAR(500) null,
	hotelRecoveryAmt VARCHAR(75) null,
	hotelRecoveryStatus INTEGER,
	hotelRecoveryApproved BOOLEAN,
	hotelRecoveryComment VARCHAR(500) null,
	internationalRecoveryAmt VARCHAR(75) null,
	internationalRecoveryStatus INTEGER,
	internationalRecoveryApproved BOOLEAN,
	internationalRecoveryComment VARCHAR(500) null,
	educationRecoveryAmt VARCHAR(75) null,
	educationRecoveryStatus INTEGER,
	educationRecoveryApproved BOOLEAN,
	educationRecoveryComment VARCHAR(500) null,
	joiningBonusRecoveryAmt VARCHAR(75) null,
	joiningBonusRecoveryStatus INTEGER,
	joiningRecoveryApproved BOOLEAN,
	joiningRecoveryComment VARCHAR(500) null,
	noticePeriodRecoveryAmt VARCHAR(75) null,
	noticePeriodRecoveryStatus INTEGER,
	noticePeriodRecoveryApproved BOOLEAN,
	noticePeriodRecoveryComment VARCHAR(500) null,
	updatedDate DATE null
);

create table NOTICE_HrForm (
	id_ LONG not null primary key,
	exitId LONG,
	foodOption LONG,
	foodOptionRemark VARCHAR(200) null,
	inductionFeedbackStatus INTEGER,
	inductionFeedbackRemark VARCHAR(200) null,
	inductionQuizStatus INTEGER,
	inductionQuizRemark VARCHAR(200) null,
	trainingFeedbackStatus INTEGER,
	trainingFeedbackRemark VARCHAR(200) null,
	exitInterviewStatus INTEGER,
	exitInterviewRemark VARCHAR(200) null,
	employeeDirectoryStatus INTEGER,
	employeeDirectoryRemark VARCHAR(200) null,
	lmsStatus INTEGER,
	lmsRemark VARCHAR(200) null,
	vantageCircleStatus INTEGER,
	vantageCircleRemark VARCHAR(200) null,
	birthdaySynergyStatus INTEGER,
	birthdaySynergyRemark VARCHAR(200) null,
	experienceLetterStatus INTEGER,
	experienceLetterRemark VARCHAR(200) null,
	ndaFormStatus INTEGER,
	ndaFormRemark VARCHAR(200) null,
	separationDocumentStatus INTEGER,
	separationDocumentRemark VARCHAR(200) null,
	trainingAgreementAmt VARCHAR(75) null,
	trainingAgreementStatus INTEGER,
	recoverableBonusAmt VARCHAR(75) null,
	recoverableBonusStatus INTEGER,
	noticePeriodRecoveryAmt VARCHAR(75) null,
	noticePeriodRecoveryStatus INTEGER,
	leavesMonth1 VARCHAR(75) null,
	leaveDaysMonth1 VARCHAR(75) null,
	leaveDateMonth1 VARCHAR(75) null,
	leavesMonth2 VARCHAR(75) null,
	leaveDaysMonth2 VARCHAR(75) null,
	leaveDateMonth2 VARCHAR(75) null,
	leavesMonth3 VARCHAR(75) null,
	leaveDaysMonth3 VARCHAR(75) null,
	leaveDateMonth3 VARCHAR(75) null,
	lopMonth1 VARCHAR(75) null,
	lopDaysMonth1 VARCHAR(75) null,
	lopDateMonth1 VARCHAR(75) null,
	lopMonth2 VARCHAR(75) null,
	lopDaysMonth2 VARCHAR(75) null,
	lopDateMonth2 VARCHAR(75) null,
	lopMonth3 VARCHAR(75) null,
	lopDaysMonth3 VARCHAR(75) null,
	lopDateMonth3 VARCHAR(75) null,
	earnedLeaveBalance VARCHAR(75) null,
	hrRemark VARCHAR(500) null,
	updatedDate DATE null
);

create table NOTICE_ItForm (
	id_ LONG not null primary key,
	exitId LONG,
	ticketNo INTEGER,
	ticketNoRemark VARCHAR(200) null,
	mailPst INTEGER,
	mailPstRemark VARCHAR(200) null,
	downloadFolder INTEGER,
	downloadFolderRemark VARCHAR(200) null,
	documentFolder INTEGER,
	documentFolderRemark VARCHAR(200) null,
	otherData INTEGER,
	otherDataRemark VARCHAR(200) null,
	googleDrive INTEGER,
	googleDriveRemark VARCHAR(200) null,
	others INTEGER,
	othersRemark VARCHAR(200) null,
	mailForwarding INTEGER,
	mailForwardingRemark VARCHAR(200) null,
	emailDisable INTEGER,
	emailDisableRemark VARCHAR(200) null,
	systemRecovered INTEGER,
	systemRecoveredRemark VARCHAR(200) null,
	clientSystemRecovered INTEGER,
	clientSystemRecoveredRemark VARCHAR(200) null,
	accessCardDisable INTEGER,
	accessCardDisableRemark VARCHAR(200) null,
	separationDocument INTEGER,
	separationDocumentRemark VARCHAR(200) null,
	systemRecoveryAmt VARCHAR(75) null,
	systemRecoveryAmtStatus INTEGER,
	systemRecoveryApproved BOOLEAN,
	systemRecoveryComment VARCHAR(500) null,
	laptopRecoveryAmt VARCHAR(75) null,
	laptopRecoveryAmtStatus INTEGER,
	laptopRecoveryApproved BOOLEAN,
	laptopRecoveryComment VARCHAR(500) null,
	communicationRecoveryAmt VARCHAR(75) null,
	communicationRecoveryStatus INTEGER,
	communicationRecoveryApproved BOOLEAN,
	communicationRecoveryComment VARCHAR(500) null,
	headphoneRecoveryAmt VARCHAR(75) null,
	headphoneRecoveryAmtStatus INTEGER,
	headphoneRecoveryApproved BOOLEAN,
	headphoneRecoveryComment VARCHAR(500) null,
	laptopBagRecoveryAmt VARCHAR(75) null,
	laptopBagRecoveryAmtStatus INTEGER,
	laptopBagRecoveryApproved BOOLEAN,
	laptopBagRecoveryComment VARCHAR(500) null,
	monitorRecoveryAmt VARCHAR(75) null,
	monitorRecoveryAmtStatus INTEGER,
	monitorRecoveryApproved BOOLEAN,
	monitorRecoveryComment VARCHAR(500) null,
	chargerRecoveryAmt VARCHAR(75) null,
	chargerRecoveryAmtStatus INTEGER,
	chargerRecoveryApproved BOOLEAN,
	chargerRecoveryComment VARCHAR(500) null,
	mouseRecoveryAmt VARCHAR(75) null,
	mouseRecoveryAmtStatus INTEGER,
	mouseRecoveryApproved BOOLEAN,
	mouseRecoveryComment VARCHAR(500) null,
	updatedDate DATE null
);

create table NOTICE_ManagerForm (
	id_ LONG not null primary key,
	exitId LONG,
	ticketNo INTEGER,
	ticketNoRemark VARCHAR(200) null,
	separationDocument INTEGER,
	separationDocumentRemark VARCHAR(200) null,
	updatedDate DATE null
);

create table NOTICE_QuestionnaireForm (
	id_ LONG not null primary key,
	resignationId LONG,
	workExperience VARCHAR(75) null,
	communicationWithEmployees VARCHAR(75) null,
	trainingOpportunity VARCHAR(75) null,
	dealingWithStaff VARCHAR(75) null,
	satisfactionLevel VARCHAR(75) null,
	reasonForLeaving VARCHAR(75) null,
	reasonForLeavingDescribe VARCHAR(300) null,
	reasonForJoining VARCHAR(300) null,
	workAgain INTEGER,
	notWorkAgain VARCHAR(300) null,
	recommendTrantor INTEGER,
	notRecommendTrantor VARCHAR(300) null,
	companyName VARCHAR(75) null,
	companyDetails VARCHAR(300) null,
	designation VARCHAR(75) null,
	location   VARCHAR(75) null,
	salaryHike VARCHAR(75) null,
	feedback  VARCHAR(75) null,
	hrRemark VARCHAR(500) null,
	submittedDate DATE null
);

create table NOTICE_RecoveryReimbursement (
	id_ LONG not null primary key,
	departmentFormId LONG,
	department INTEGER,
	recoveryType BOOLEAN,
	recoveryItem VARCHAR(500) null,
	recoveryAmount VARCHAR(75) null,
	recoveryStatus INTEGER,
	reimbursementItem VARCHAR(500) null,
	reimbursementAmount VARCHAR(75) null,
	reimbursementStatus INTEGER,
	approved BOOLEAN,
	comment_ VARCHAR(500) null
);

create table NOTICE_Resignation (
	id_ LONG not null primary key,
	ecode VARCHAR(75) null,
	account VARCHAR(75) null,
	managerEmail VARCHAR(75) null,
	assigneeEmail VARCHAR(75) null,
	assigneeTo BOOLEAN,
	alternateEmail VARCHAR(75) null,
	stateName VARCHAR(75) null,
	cityName VARCHAR(75) null,
	pincode VARCHAR(75) null,
	postalAddress VARCHAR(500) null,
	reason VARCHAR(75) null,
	lastWorkingDate DATE null,
	managerSubmissionDate DATE null,
	hrSubmissionDate DATE null,
	withdrawInitiatedDate DATE null,
	abscondTerminateDate DATE null,
	separationType VARCHAR(75) null,
	keyToCompany VARCHAR(75) null,
	keyToProject VARCHAR(75) null,
	rating VARCHAR(75) null,
	clientImpact VARCHAR(75) null,
	keyToRetention VARCHAR(75) null,
	reasonNonRetention VARCHAR(75) null,
	employeeComment VARCHAR(500) null,
	hrComment VARCHAR(500) null,
	managerComment VARCHAR(500) null,
	empWithdrawComment VARCHAR(500) null,
	hrWithdrawComment VARCHAR(500) null,
	reasonForLeaving VARCHAR(75) null,
	reasonForLeavingByHr VARCHAR(75) null,
	eligibleForRehire VARCHAR(75) null,
	otherIssue VARCHAR(75) null,
	replacementPlan VARCHAR(75) null,
	replacementDetail VARCHAR(75) null,
	status INTEGER,
	terminationType VARCHAR(75) null,
	creationDate DATE null,
	initiatedDate DATE null,
	mobile VARCHAR(75) null,
	noticePeriod VARCHAR(75) null,
	itAssetsSubmissionDate DATE null,
	retainEmployeeDate DATE null,
	hasLaptop VARCHAR(75) null,
	hasMouse VARCHAR(75) null,
	hasCharger VARCHAR(75) null,
	hasHeadSet VARCHAR(75) null,
	hasLaptopBag VARCHAR(75) null,
	hasHomeDesktop VARCHAR(75) null,
	hasHomeMonitor VARCHAR(75) null,
	otherAssetsList VARCHAR(500) null,
	exitQuestionnaire BOOLEAN,
	withdrawCount INTEGER
);