/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.probation.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProbationLine service. Represents a row in the &quot;PROBATION_ProbationLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.probation.core.model.impl.ProbationLineModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.probation.core.model.impl.ProbationLineImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProbationLine
 * @generated
 */
@ProviderType
public interface ProbationLineModel extends BaseModel<ProbationLine> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a probation line model instance should use the {@link ProbationLine} interface instead.
	 */

	/**
	 * Returns the primary key of this probation line.
	 *
	 * @return the primary key of this probation line
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this probation line.
	 *
	 * @param primaryKey the primary key of this probation line
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the line ID of this probation line.
	 *
	 * @return the line ID of this probation line
	 */
	public long getLineId();

	/**
	 * Sets the line ID of this probation line.
	 *
	 * @param lineId the line ID of this probation line
	 */
	public void setLineId(long lineId);

	/**
	 * Returns the probation ID of this probation line.
	 *
	 * @return the probation ID of this probation line
	 */
	@AutoEscape
	public String getProbationId();

	/**
	 * Sets the probation ID of this probation line.
	 *
	 * @param probationId the probation ID of this probation line
	 */
	public void setProbationId(String probationId);

	/**
	 * Returns the line number of this probation line.
	 *
	 * @return the line number of this probation line
	 */
	public int getLineNumber();

	/**
	 * Sets the line number of this probation line.
	 *
	 * @param lineNumber the line number of this probation line
	 */
	public void setLineNumber(int lineNumber);

	/**
	 * Returns the rating of this probation line.
	 *
	 * @return the rating of this probation line
	 */
	public int getRating();

	/**
	 * Sets the rating of this probation line.
	 *
	 * @param rating the rating of this probation line
	 */
	public void setRating(int rating);

	/**
	 * Returns the comment of this probation line.
	 *
	 * @return the comment of this probation line
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this probation line.
	 *
	 * @param comment the comment of this probation line
	 */
	public void setComment(String comment);

	@Override
	public ProbationLine cloneWithOriginalValues();

}