/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.probation.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.probation.core.model.ProbationLine;
import com.trantorinc.synergy.probation.core.model.ProbationLineModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProbationLine service. Represents a row in the &quot;PROBATION_ProbationLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProbationLineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProbationLineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProbationLineImpl
 * @generated
 */
public class ProbationLineModelImpl
	extends BaseModelImpl<ProbationLine> implements ProbationLineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a probation line model instance should use the <code>ProbationLine</code> interface instead.
	 */
	public static final String TABLE_NAME = "PROBATION_ProbationLine";

	public static final Object[][] TABLE_COLUMNS = {
		{"lineId", Types.BIGINT}, {"probationId", Types.VARCHAR},
		{"lineNumber", Types.INTEGER}, {"rating", Types.INTEGER},
		{"comment_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("probationId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lineNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("rating", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("comment_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PROBATION_ProbationLine (lineId LONG not null primary key,probationId VARCHAR(75) null,lineNumber INTEGER,rating INTEGER,comment_ VARCHAR(300) null)";

	public static final String TABLE_SQL_DROP =
		"drop table PROBATION_ProbationLine";

	public static final String ORDER_BY_JPQL =
		" ORDER BY probationLine.lineNumber ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PROBATION_ProbationLine.lineNumber ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LINENUMBER_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProbationLineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProbationLine.class;
	}

	@Override
	public String getModelClassName() {
		return ProbationLine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProbationLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProbationLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProbationLine, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProbationLine)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProbationLine, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProbationLine, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProbationLine)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProbationLine, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProbationLine, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProbationLine, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProbationLine, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProbationLine, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ProbationLine, Object>>();
		Map<String, BiConsumer<ProbationLine, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ProbationLine, ?>>();

		attributeGetterFunctions.put("lineId", ProbationLine::getLineId);
		attributeSetterBiConsumers.put(
			"lineId",
			(BiConsumer<ProbationLine, Long>)ProbationLine::setLineId);
		attributeGetterFunctions.put(
			"probationId", ProbationLine::getProbationId);
		attributeSetterBiConsumers.put(
			"probationId",
			(BiConsumer<ProbationLine, String>)ProbationLine::setProbationId);
		attributeGetterFunctions.put(
			"lineNumber", ProbationLine::getLineNumber);
		attributeSetterBiConsumers.put(
			"lineNumber",
			(BiConsumer<ProbationLine, Integer>)ProbationLine::setLineNumber);
		attributeGetterFunctions.put("rating", ProbationLine::getRating);
		attributeSetterBiConsumers.put(
			"rating",
			(BiConsumer<ProbationLine, Integer>)ProbationLine::setRating);
		attributeGetterFunctions.put("comment", ProbationLine::getComment);
		attributeSetterBiConsumers.put(
			"comment",
			(BiConsumer<ProbationLine, String>)ProbationLine::setComment);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLineId() {
		return _lineId;
	}

	@Override
	public void setLineId(long lineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lineId = lineId;
	}

	@Override
	public String getProbationId() {
		if (_probationId == null) {
			return "";
		}
		else {
			return _probationId;
		}
	}

	@Override
	public void setProbationId(String probationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationId = probationId;
	}

	@Override
	public int getLineNumber() {
		return _lineNumber;
	}

	@Override
	public void setLineNumber(int lineNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lineNumber = lineNumber;
	}

	@Override
	public int getRating() {
		return _rating;
	}

	@Override
	public void setRating(int rating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rating = rating;
	}

	@Override
	public String getComment() {
		if (_comment == null) {
			return "";
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comment = comment;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProbationLine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProbationLine toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProbationLine>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProbationLineImpl probationLineImpl = new ProbationLineImpl();

		probationLineImpl.setLineId(getLineId());
		probationLineImpl.setProbationId(getProbationId());
		probationLineImpl.setLineNumber(getLineNumber());
		probationLineImpl.setRating(getRating());
		probationLineImpl.setComment(getComment());

		probationLineImpl.resetOriginalValues();

		return probationLineImpl;
	}

	@Override
	public ProbationLine cloneWithOriginalValues() {
		ProbationLineImpl probationLineImpl = new ProbationLineImpl();

		probationLineImpl.setLineId(
			this.<Long>getColumnOriginalValue("lineId"));
		probationLineImpl.setProbationId(
			this.<String>getColumnOriginalValue("probationId"));
		probationLineImpl.setLineNumber(
			this.<Integer>getColumnOriginalValue("lineNumber"));
		probationLineImpl.setRating(
			this.<Integer>getColumnOriginalValue("rating"));
		probationLineImpl.setComment(
			this.<String>getColumnOriginalValue("comment_"));

		return probationLineImpl;
	}

	@Override
	public int compareTo(ProbationLine probationLine) {
		int value = 0;

		if (getLineNumber() < probationLine.getLineNumber()) {
			value = -1;
		}
		else if (getLineNumber() > probationLine.getLineNumber()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProbationLine)) {
			return false;
		}

		ProbationLine probationLine = (ProbationLine)object;

		long primaryKey = probationLine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProbationLine> toCacheModel() {
		ProbationLineCacheModel probationLineCacheModel =
			new ProbationLineCacheModel();

		probationLineCacheModel.lineId = getLineId();

		probationLineCacheModel.probationId = getProbationId();

		String probationId = probationLineCacheModel.probationId;

		if ((probationId != null) && (probationId.length() == 0)) {
			probationLineCacheModel.probationId = null;
		}

		probationLineCacheModel.lineNumber = getLineNumber();

		probationLineCacheModel.rating = getRating();

		probationLineCacheModel.comment = getComment();

		String comment = probationLineCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			probationLineCacheModel.comment = null;
		}

		return probationLineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProbationLine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProbationLine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProbationLine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProbationLine)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProbationLine>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProbationLine.class, ModelWrapper.class);

	}

	private long _lineId;
	private String _probationId;
	private int _lineNumber;
	private int _rating;
	private String _comment;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProbationLine, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProbationLine)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("lineId", _lineId);
		_columnOriginalValues.put("probationId", _probationId);
		_columnOriginalValues.put("lineNumber", _lineNumber);
		_columnOriginalValues.put("rating", _rating);
		_columnOriginalValues.put("comment_", _comment);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("comment_", "comment");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("lineId", 1L);

		columnBitmasks.put("probationId", 2L);

		columnBitmasks.put("lineNumber", 4L);

		columnBitmasks.put("rating", 8L);

		columnBitmasks.put("comment_", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProbationLine _escapedModel;

}