/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.skill.core.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.trantorinc.synergy.skill.core.model.SkillRejectionComment;
import com.trantorinc.synergy.skill.core.model.SkillRejectionCommentModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SkillRejectionComment service. Represents a row in the &quot;SKILL_SkillRejectionComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SkillRejectionCommentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SkillRejectionCommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SkillRejectionCommentImpl
 * @generated
 */
public class SkillRejectionCommentModelImpl
	extends BaseModelImpl<SkillRejectionComment>
	implements SkillRejectionCommentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skill rejection comment model instance should use the <code>SkillRejectionComment</code> interface instead.
	 */
	public static final String TABLE_NAME = "SKILL_SkillRejectionComment";

	public static final Object[][] TABLE_COLUMNS = {
		{"commentId", Types.BIGINT}, {"ecode", Types.VARCHAR},
		{"author", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"createdDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ecode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("author", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SKILL_SkillRejectionComment (commentId LONG not null primary key,ecode VARCHAR(75) null,author VARCHAR(75) null,description VARCHAR(1000) null,createdDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SKILL_SkillRejectionComment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY skillRejectionComment.commentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SKILL_SkillRejectionComment.commentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SkillRejectionCommentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SkillRejectionComment.class;
	}

	@Override
	public String getModelClassName() {
		return SkillRejectionComment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SkillRejectionComment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SkillRejectionComment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkillRejectionComment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SkillRejectionComment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SkillRejectionComment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SkillRejectionComment, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SkillRejectionComment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SkillRejectionComment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SkillRejectionComment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SkillRejectionComment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SkillRejectionComment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SkillRejectionComment, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SkillRejectionComment, Object>>();
		Map<String, BiConsumer<SkillRejectionComment, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<SkillRejectionComment, ?>>();

		attributeGetterFunctions.put(
			"commentId", SkillRejectionComment::getCommentId);
		attributeSetterBiConsumers.put(
			"commentId",
			(BiConsumer<SkillRejectionComment, Long>)
				SkillRejectionComment::setCommentId);
		attributeGetterFunctions.put("ecode", SkillRejectionComment::getEcode);
		attributeSetterBiConsumers.put(
			"ecode",
			(BiConsumer<SkillRejectionComment, String>)
				SkillRejectionComment::setEcode);
		attributeGetterFunctions.put(
			"author", SkillRejectionComment::getAuthor);
		attributeSetterBiConsumers.put(
			"author",
			(BiConsumer<SkillRejectionComment, String>)
				SkillRejectionComment::setAuthor);
		attributeGetterFunctions.put(
			"description", SkillRejectionComment::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<SkillRejectionComment, String>)
				SkillRejectionComment::setDescription);
		attributeGetterFunctions.put(
			"createdDate", SkillRejectionComment::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<SkillRejectionComment, Date>)
				SkillRejectionComment::setCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCommentId() {
		return _commentId;
	}

	@Override
	public void setCommentId(long commentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commentId = commentId;
	}

	@Override
	public String getEcode() {
		if (_ecode == null) {
			return "";
		}
		else {
			return _ecode;
		}
	}

	@Override
	public void setEcode(String ecode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ecode = ecode;
	}

	@Override
	public String getAuthor() {
		if (_author == null) {
			return "";
		}
		else {
			return _author;
		}
	}

	@Override
	public void setAuthor(String author) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_author = author;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SkillRejectionComment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SkillRejectionComment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SkillRejectionComment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SkillRejectionCommentImpl skillRejectionCommentImpl =
			new SkillRejectionCommentImpl();

		skillRejectionCommentImpl.setCommentId(getCommentId());
		skillRejectionCommentImpl.setEcode(getEcode());
		skillRejectionCommentImpl.setAuthor(getAuthor());
		skillRejectionCommentImpl.setDescription(getDescription());
		skillRejectionCommentImpl.setCreatedDate(getCreatedDate());

		skillRejectionCommentImpl.resetOriginalValues();

		return skillRejectionCommentImpl;
	}

	@Override
	public SkillRejectionComment cloneWithOriginalValues() {
		SkillRejectionCommentImpl skillRejectionCommentImpl =
			new SkillRejectionCommentImpl();

		skillRejectionCommentImpl.setCommentId(
			this.<Long>getColumnOriginalValue("commentId"));
		skillRejectionCommentImpl.setEcode(
			this.<String>getColumnOriginalValue("ecode"));
		skillRejectionCommentImpl.setAuthor(
			this.<String>getColumnOriginalValue("author"));
		skillRejectionCommentImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		skillRejectionCommentImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("createdDate"));

		return skillRejectionCommentImpl;
	}

	@Override
	public int compareTo(SkillRejectionComment skillRejectionComment) {
		long primaryKey = skillRejectionComment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SkillRejectionComment)) {
			return false;
		}

		SkillRejectionComment skillRejectionComment =
			(SkillRejectionComment)object;

		long primaryKey = skillRejectionComment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SkillRejectionComment> toCacheModel() {
		SkillRejectionCommentCacheModel skillRejectionCommentCacheModel =
			new SkillRejectionCommentCacheModel();

		skillRejectionCommentCacheModel.commentId = getCommentId();

		skillRejectionCommentCacheModel.ecode = getEcode();

		String ecode = skillRejectionCommentCacheModel.ecode;

		if ((ecode != null) && (ecode.length() == 0)) {
			skillRejectionCommentCacheModel.ecode = null;
		}

		skillRejectionCommentCacheModel.author = getAuthor();

		String author = skillRejectionCommentCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			skillRejectionCommentCacheModel.author = null;
		}

		skillRejectionCommentCacheModel.description = getDescription();

		String description = skillRejectionCommentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			skillRejectionCommentCacheModel.description = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			skillRejectionCommentCacheModel.createdDate = createdDate.getTime();
		}
		else {
			skillRejectionCommentCacheModel.createdDate = Long.MIN_VALUE;
		}

		return skillRejectionCommentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SkillRejectionComment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SkillRejectionComment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkillRejectionComment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SkillRejectionComment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SkillRejectionComment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SkillRejectionComment.class, ModelWrapper.class);

	}

	private long _commentId;
	private String _ecode;
	private String _author;
	private String _description;
	private Date _createdDate;

	public <T> T getColumnValue(String columnName) {
		Function<SkillRejectionComment, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SkillRejectionComment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("commentId", _commentId);
		_columnOriginalValues.put("ecode", _ecode);
		_columnOriginalValues.put("author", _author);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("createdDate", _createdDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("commentId", 1L);

		columnBitmasks.put("ecode", 2L);

		columnBitmasks.put("author", 4L);

		columnBitmasks.put("description", 8L);

		columnBitmasks.put("createdDate", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SkillRejectionComment _escapedModel;

}