/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.skill.core.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.trantorinc.synergy.skill.core.model.SkillRejectionComment;
import com.trantorinc.synergy.skill.core.service.SkillRejectionCommentLocalService;
import com.trantorinc.synergy.skill.core.service.SkillRejectionCommentLocalServiceUtil;
import com.trantorinc.synergy.skill.core.service.persistence.CertificateFinder;
import com.trantorinc.synergy.skill.core.service.persistence.CertificatePersistence;
import com.trantorinc.synergy.skill.core.service.persistence.SkillFinder;
import com.trantorinc.synergy.skill.core.service.persistence.SkillGuidePersistence;
import com.trantorinc.synergy.skill.core.service.persistence.SkillPersistence;
import com.trantorinc.synergy.skill.core.service.persistence.SkillRejectionCommentFinder;
import com.trantorinc.synergy.skill.core.service.persistence.SkillRejectionCommentPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the skill rejection comment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.trantorinc.synergy.skill.core.service.impl.SkillRejectionCommentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.trantorinc.synergy.skill.core.service.impl.SkillRejectionCommentLocalServiceImpl
 * @generated
 */
public abstract class SkillRejectionCommentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   SkillRejectionCommentLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SkillRejectionCommentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SkillRejectionCommentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the skill rejection comment to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SkillRejectionCommentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param skillRejectionComment the skill rejection comment
	 * @return the skill rejection comment that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SkillRejectionComment addSkillRejectionComment(
		SkillRejectionComment skillRejectionComment) {

		skillRejectionComment.setNew(true);

		return skillRejectionCommentPersistence.update(skillRejectionComment);
	}

	/**
	 * Creates a new skill rejection comment with the primary key. Does not add the skill rejection comment to the database.
	 *
	 * @param commentId the primary key for the new skill rejection comment
	 * @return the new skill rejection comment
	 */
	@Override
	@Transactional(enabled = false)
	public SkillRejectionComment createSkillRejectionComment(long commentId) {
		return skillRejectionCommentPersistence.create(commentId);
	}

	/**
	 * Deletes the skill rejection comment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SkillRejectionCommentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commentId the primary key of the skill rejection comment
	 * @return the skill rejection comment that was removed
	 * @throws PortalException if a skill rejection comment with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SkillRejectionComment deleteSkillRejectionComment(long commentId)
		throws PortalException {

		return skillRejectionCommentPersistence.remove(commentId);
	}

	/**
	 * Deletes the skill rejection comment from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SkillRejectionCommentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param skillRejectionComment the skill rejection comment
	 * @return the skill rejection comment that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SkillRejectionComment deleteSkillRejectionComment(
		SkillRejectionComment skillRejectionComment) {

		return skillRejectionCommentPersistence.remove(skillRejectionComment);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return skillRejectionCommentPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SkillRejectionComment.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return skillRejectionCommentPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.skill.core.model.impl.SkillRejectionCommentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return skillRejectionCommentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.skill.core.model.impl.SkillRejectionCommentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return skillRejectionCommentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return skillRejectionCommentPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return skillRejectionCommentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SkillRejectionComment fetchSkillRejectionComment(long commentId) {
		return skillRejectionCommentPersistence.fetchByPrimaryKey(commentId);
	}

	/**
	 * Returns the skill rejection comment with the primary key.
	 *
	 * @param commentId the primary key of the skill rejection comment
	 * @return the skill rejection comment
	 * @throws PortalException if a skill rejection comment with the primary key could not be found
	 */
	@Override
	public SkillRejectionComment getSkillRejectionComment(long commentId)
		throws PortalException {

		return skillRejectionCommentPersistence.findByPrimaryKey(commentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			skillRejectionCommentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SkillRejectionComment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("commentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			skillRejectionCommentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			SkillRejectionComment.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("commentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			skillRejectionCommentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SkillRejectionComment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("commentId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return skillRejectionCommentPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement SkillRejectionCommentLocalServiceImpl#deleteSkillRejectionComment(SkillRejectionComment) to avoid orphaned data");
		}

		return skillRejectionCommentLocalService.deleteSkillRejectionComment(
			(SkillRejectionComment)persistedModel);
	}

	@Override
	public BasePersistence<SkillRejectionComment> getBasePersistence() {
		return skillRejectionCommentPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return skillRejectionCommentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the skill rejection comments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.trantorinc.synergy.skill.core.model.impl.SkillRejectionCommentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of skill rejection comments
	 * @param end the upper bound of the range of skill rejection comments (not inclusive)
	 * @return the range of skill rejection comments
	 */
	@Override
	public List<SkillRejectionComment> getSkillRejectionComments(
		int start, int end) {

		return skillRejectionCommentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of skill rejection comments.
	 *
	 * @return the number of skill rejection comments
	 */
	@Override
	public int getSkillRejectionCommentsCount() {
		return skillRejectionCommentPersistence.countAll();
	}

	/**
	 * Updates the skill rejection comment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SkillRejectionCommentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param skillRejectionComment the skill rejection comment
	 * @return the skill rejection comment that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SkillRejectionComment updateSkillRejectionComment(
		SkillRejectionComment skillRejectionComment) {

		return skillRejectionCommentPersistence.update(skillRejectionComment);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SkillRejectionCommentLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		skillRejectionCommentLocalService =
			(SkillRejectionCommentLocalService)aopProxy;

		_setLocalServiceUtilService(skillRejectionCommentLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SkillRejectionCommentLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SkillRejectionComment.class;
	}

	protected String getModelClassName() {
		return SkillRejectionComment.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				skillRejectionCommentPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		SkillRejectionCommentLocalService skillRejectionCommentLocalService) {

		try {
			Field field =
				SkillRejectionCommentLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, skillRejectionCommentLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CertificatePersistence certificatePersistence;

	@Reference
	protected CertificateFinder certificateFinder;

	@Reference
	protected SkillPersistence skillPersistence;

	@Reference
	protected SkillFinder skillFinder;

	@Reference
	protected SkillGuidePersistence skillGuidePersistence;

	protected SkillRejectionCommentLocalService
		skillRejectionCommentLocalService;

	@Reference
	protected SkillRejectionCommentPersistence skillRejectionCommentPersistence;

	@Reference
	protected SkillRejectionCommentFinder skillRejectionCommentFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SkillRejectionCommentLocalServiceBaseImpl.class);

}