/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.skill.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Certificate service. Represents a row in the &quot;SKILL_Certificate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.skill.core.model.impl.CertificateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.skill.core.model.impl.CertificateImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Certificate
 * @generated
 */
@ProviderType
public interface CertificateModel extends BaseModel<Certificate> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a certificate model instance should use the {@link Certificate} interface instead.
	 */

	/**
	 * Returns the primary key of this certificate.
	 *
	 * @return the primary key of this certificate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this certificate.
	 *
	 * @param primaryKey the primary key of this certificate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the certificate ID of this certificate.
	 *
	 * @return the certificate ID of this certificate
	 */
	public long getCertificateId();

	/**
	 * Sets the certificate ID of this certificate.
	 *
	 * @param certificateId the certificate ID of this certificate
	 */
	public void setCertificateId(long certificateId);

	/**
	 * Returns the ecode of this certificate.
	 *
	 * @return the ecode of this certificate
	 */
	@AutoEscape
	public String getEcode();

	/**
	 * Sets the ecode of this certificate.
	 *
	 * @param ecode the ecode of this certificate
	 */
	public void setEcode(String ecode);

	/**
	 * Returns the name of this certificate.
	 *
	 * @return the name of this certificate
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this certificate.
	 *
	 * @param name the name of this certificate
	 */
	public void setName(String name);

	/**
	 * Returns the category of this certificate.
	 *
	 * @return the category of this certificate
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this certificate.
	 *
	 * @param category the category of this certificate
	 */
	public void setCategory(String category);

	/**
	 * Returns the description of this certificate.
	 *
	 * @return the description of this certificate
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this certificate.
	 *
	 * @param description the description of this certificate
	 */
	public void setDescription(String description);

	/**
	 * Returns the file ID of this certificate.
	 *
	 * @return the file ID of this certificate
	 */
	@AutoEscape
	public String getFileId();

	/**
	 * Sets the file ID of this certificate.
	 *
	 * @param fileId the file ID of this certificate
	 */
	public void setFileId(String fileId);

	/**
	 * Returns the filename of this certificate.
	 *
	 * @return the filename of this certificate
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this certificate.
	 *
	 * @param filename the filename of this certificate
	 */
	public void setFilename(String filename);

	/**
	 * Returns the created date of this certificate.
	 *
	 * @return the created date of this certificate
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this certificate.
	 *
	 * @param createdDate the created date of this certificate
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the expiry date of this certificate.
	 *
	 * @return the expiry date of this certificate
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this certificate.
	 *
	 * @param expiryDate the expiry date of this certificate
	 */
	public void setExpiryDate(Date expiryDate);

	@Override
	public Certificate cloneWithOriginalValues();

}