/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.skill.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SkillGuide service. Represents a row in the &quot;SKILL_SkillGuide&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.skill.core.model.impl.SkillGuideModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.skill.core.model.impl.SkillGuideImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SkillGuide
 * @generated
 */
@ProviderType
public interface SkillGuideModel extends BaseModel<SkillGuide> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skill guide model instance should use the {@link SkillGuide} interface instead.
	 */

	/**
	 * Returns the primary key of this skill guide.
	 *
	 * @return the primary key of this skill guide
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skill guide.
	 *
	 * @param primaryKey the primary key of this skill guide
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the guide ID of this skill guide.
	 *
	 * @return the guide ID of this skill guide
	 */
	public long getGuideId();

	/**
	 * Sets the guide ID of this skill guide.
	 *
	 * @param guideId the guide ID of this skill guide
	 */
	public void setGuideId(long guideId);

	/**
	 * Returns the core skill of this skill guide.
	 *
	 * @return the core skill of this skill guide
	 */
	@AutoEscape
	public String getCoreSkill();

	/**
	 * Sets the core skill of this skill guide.
	 *
	 * @param coreSkill the core skill of this skill guide
	 */
	public void setCoreSkill(String coreSkill);

	/**
	 * Returns the sub skill of this skill guide.
	 *
	 * @return the sub skill of this skill guide
	 */
	@AutoEscape
	public String getSubSkill();

	/**
	 * Sets the sub skill of this skill guide.
	 *
	 * @param subSkill the sub skill of this skill guide
	 */
	public void setSubSkill(String subSkill);

	@Override
	public SkillGuide cloneWithOriginalValues();

}