/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.skill.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SkillRejectionComment service. Represents a row in the &quot;SKILL_SkillRejectionComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.skill.core.model.impl.SkillRejectionCommentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.skill.core.model.impl.SkillRejectionCommentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SkillRejectionComment
 * @generated
 */
@ProviderType
public interface SkillRejectionCommentModel
	extends BaseModel<SkillRejectionComment> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skill rejection comment model instance should use the {@link SkillRejectionComment} interface instead.
	 */

	/**
	 * Returns the primary key of this skill rejection comment.
	 *
	 * @return the primary key of this skill rejection comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skill rejection comment.
	 *
	 * @param primaryKey the primary key of this skill rejection comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comment ID of this skill rejection comment.
	 *
	 * @return the comment ID of this skill rejection comment
	 */
	public long getCommentId();

	/**
	 * Sets the comment ID of this skill rejection comment.
	 *
	 * @param commentId the comment ID of this skill rejection comment
	 */
	public void setCommentId(long commentId);

	/**
	 * Returns the ecode of this skill rejection comment.
	 *
	 * @return the ecode of this skill rejection comment
	 */
	@AutoEscape
	public String getEcode();

	/**
	 * Sets the ecode of this skill rejection comment.
	 *
	 * @param ecode the ecode of this skill rejection comment
	 */
	public void setEcode(String ecode);

	/**
	 * Returns the author of this skill rejection comment.
	 *
	 * @return the author of this skill rejection comment
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this skill rejection comment.
	 *
	 * @param author the author of this skill rejection comment
	 */
	public void setAuthor(String author);

	/**
	 * Returns the description of this skill rejection comment.
	 *
	 * @return the description of this skill rejection comment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this skill rejection comment.
	 *
	 * @param description the description of this skill rejection comment
	 */
	public void setDescription(String description);

	/**
	 * Returns the created date of this skill rejection comment.
	 *
	 * @return the created date of this skill rejection comment
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this skill rejection comment.
	 *
	 * @param createdDate the created date of this skill rejection comment
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public SkillRejectionComment cloneWithOriginalValues();

}