/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trantorinc.synergy.expense.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Expense service. Represents a row in the &quot;EXPENSE_Expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trantorinc.synergy.expense.core.model.impl.ExpenseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trantorinc.synergy.expense.core.model.impl.ExpenseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Expense
 * @generated
 */
@ProviderType
public interface ExpenseModel extends BaseModel<Expense> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense model instance should use the {@link Expense} interface instead.
	 */

	/**
	 * Returns the primary key of this expense.
	 *
	 * @return the primary key of this expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense.
	 *
	 * @param primaryKey the primary key of this expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense ID of this expense.
	 *
	 * @return the expense ID of this expense
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense.
	 *
	 * @param expenseId the expense ID of this expense
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the ecode of this expense.
	 *
	 * @return the ecode of this expense
	 */
	@AutoEscape
	public String getEcode();

	/**
	 * Sets the ecode of this expense.
	 *
	 * @param ecode the ecode of this expense
	 */
	public void setEcode(String ecode);

	/**
	 * Returns the expense type of this expense.
	 *
	 * @return the expense type of this expense
	 */
	@AutoEscape
	public String getExpenseType();

	/**
	 * Sets the expense type of this expense.
	 *
	 * @param expenseType the expense type of this expense
	 */
	public void setExpenseType(String expenseType);

	/**
	 * Returns the total bill amount of this expense.
	 *
	 * @return the total bill amount of this expense
	 */
	public long getTotalBillAmount();

	/**
	 * Sets the total bill amount of this expense.
	 *
	 * @param totalBillAmount the total bill amount of this expense
	 */
	public void setTotalBillAmount(long totalBillAmount);

	/**
	 * Returns the assignee of this expense.
	 *
	 * @return the assignee of this expense
	 */
	@AutoEscape
	public String getAssignee();

	/**
	 * Sets the assignee of this expense.
	 *
	 * @param assignee the assignee of this expense
	 */
	public void setAssignee(String assignee);

	/**
	 * Returns the manager comment of this expense.
	 *
	 * @return the manager comment of this expense
	 */
	@AutoEscape
	public String getManagerComment();

	/**
	 * Sets the manager comment of this expense.
	 *
	 * @param managerComment the manager comment of this expense
	 */
	public void setManagerComment(String managerComment);

	/**
	 * Returns the finance comment of this expense.
	 *
	 * @return the finance comment of this expense
	 */
	@AutoEscape
	public String getFinanceComment();

	/**
	 * Sets the finance comment of this expense.
	 *
	 * @param financeComment the finance comment of this expense
	 */
	public void setFinanceComment(String financeComment);

	/**
	 * Returns the approving manager of this expense.
	 *
	 * @return the approving manager of this expense
	 */
	@AutoEscape
	public String getApprovingManager();

	/**
	 * Sets the approving manager of this expense.
	 *
	 * @param approvingManager the approving manager of this expense
	 */
	public void setApprovingManager(String approvingManager);

	/**
	 * Returns the status of this expense.
	 *
	 * @return the status of this expense
	 */
	public int getStatus();

	/**
	 * Sets the status of this expense.
	 *
	 * @param status the status of this expense
	 */
	public void setStatus(int status);

	/**
	 * Returns the created date of this expense.
	 *
	 * @return the created date of this expense
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this expense.
	 *
	 * @param createdDate the created date of this expense
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the manager date of this expense.
	 *
	 * @return the manager date of this expense
	 */
	public Date getManagerDate();

	/**
	 * Sets the manager date of this expense.
	 *
	 * @param managerDate the manager date of this expense
	 */
	public void setManagerDate(Date managerDate);

	/**
	 * Returns the finance date of this expense.
	 *
	 * @return the finance date of this expense
	 */
	public Date getFinanceDate();

	/**
	 * Sets the finance date of this expense.
	 *
	 * @param financeDate the finance date of this expense
	 */
	public void setFinanceDate(Date financeDate);

	/**
	 * Returns the file ID of this expense.
	 *
	 * @return the file ID of this expense
	 */
	@AutoEscape
	public String getFileId();

	/**
	 * Sets the file ID of this expense.
	 *
	 * @param fileId the file ID of this expense
	 */
	public void setFileId(String fileId);

	@Override
	public Expense cloneWithOriginalValues();

}